{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "8ea6f8b5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "import scikeras\n",
    "from sklearn.model_selection import train_test_split\n",
    "from scikeras.wrappers import KerasRegressor\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "059ec111",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>T1</th>\n",
       "      <th>F1</th>\n",
       "      <th>F2</th>\n",
       "      <th>F3</th>\n",
       "      <th>F4</th>\n",
       "      <th>F5</th>\n",
       "      <th>F6</th>\n",
       "      <th>T2</th>\n",
       "      <th>T3</th>\n",
       "      <th>F7</th>\n",
       "      <th>F8</th>\n",
       "      <th>F9</th>\n",
       "      <th>F10</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>520.0</th>\n",
       "      <td>2.699188</td>\n",
       "      <td>2039.344180</td>\n",
       "      <td>2.436909</td>\n",
       "      <td>116.365766</td>\n",
       "      <td>24.921719</td>\n",
       "      <td>223.057932</td>\n",
       "      <td>697.411809</td>\n",
       "      <td>71.979322</td>\n",
       "      <td>2657.645298</td>\n",
       "      <td>187.868789</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.590618</td>\n",
       "      <td>50.328563</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>900.0</th>\n",
       "      <td>1.626946</td>\n",
       "      <td>2041.009029</td>\n",
       "      <td>1121.833091</td>\n",
       "      <td>109.410886</td>\n",
       "      <td>24.189351</td>\n",
       "      <td>290.533547</td>\n",
       "      <td>345.736723</td>\n",
       "      <td>74.713688</td>\n",
       "      <td>2045.587154</td>\n",
       "      <td>230.681137</td>\n",
       "      <td>1.0</td>\n",
       "      <td>8.697175</td>\n",
       "      <td>70.523926</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1018.0</th>\n",
       "      <td>2.271346</td>\n",
       "      <td>1952.087902</td>\n",
       "      <td>912.855545</td>\n",
       "      <td>86.992183</td>\n",
       "      <td>20.123249</td>\n",
       "      <td>324.774576</td>\n",
       "      <td>209.198700</td>\n",
       "      <td>73.090961</td>\n",
       "      <td>2387.292495</td>\n",
       "      <td>125.007669</td>\n",
       "      <td>1.0</td>\n",
       "      <td>9.076380</td>\n",
       "      <td>47.019770</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>741.0</th>\n",
       "      <td>1.562514</td>\n",
       "      <td>2020.005530</td>\n",
       "      <td>1649.415706</td>\n",
       "      <td>59.496316</td>\n",
       "      <td>16.779820</td>\n",
       "      <td>221.332443</td>\n",
       "      <td>450.292990</td>\n",
       "      <td>67.887882</td>\n",
       "      <td>2175.645308</td>\n",
       "      <td>90.402162</td>\n",
       "      <td>1.0</td>\n",
       "      <td>5.167153</td>\n",
       "      <td>49.196801</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>367.0</th>\n",
       "      <td>2.717755</td>\n",
       "      <td>2092.178750</td>\n",
       "      <td>21.771994</td>\n",
       "      <td>48.087114</td>\n",
       "      <td>26.105167</td>\n",
       "      <td>289.494401</td>\n",
       "      <td>8.460317</td>\n",
       "      <td>71.617030</td>\n",
       "      <td>2680.194401</td>\n",
       "      <td>212.637811</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.117312</td>\n",
       "      <td>45.541835</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "              T1           F1           F2          F3         F4          F5  \\\n",
       "520.0   2.699188  2039.344180     2.436909  116.365766  24.921719  223.057932   \n",
       "900.0   1.626946  2041.009029  1121.833091  109.410886  24.189351  290.533547   \n",
       "1018.0  2.271346  1952.087902   912.855545   86.992183  20.123249  324.774576   \n",
       "741.0   1.562514  2020.005530  1649.415706   59.496316  16.779820  221.332443   \n",
       "367.0   2.717755  2092.178750    21.771994   48.087114  26.105167  289.494401   \n",
       "\n",
       "                F6         T2           T3          F7   F8        F9  \\\n",
       "520.0   697.411809  71.979322  2657.645298  187.868789  0.0  4.590618   \n",
       "900.0   345.736723  74.713688  2045.587154  230.681137  1.0  8.697175   \n",
       "1018.0  209.198700  73.090961  2387.292495  125.007669  1.0  9.076380   \n",
       "741.0   450.292990  67.887882  2175.645308   90.402162  1.0  5.167153   \n",
       "367.0     8.460317  71.617030  2680.194401  212.637811  0.0  6.117312   \n",
       "\n",
       "              F10  \n",
       "520.0   50.328563  \n",
       "900.0   70.523926  \n",
       "1018.0  47.019770  \n",
       "741.0   49.196801  \n",
       "367.0   45.541835  "
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv('data_model.csv', index_col = 0)\n",
    "df.sample(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "ea6d5932",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_1 = df.drop(['F1', 'F4', 'F5', 'F6', 'T2', 'F7', 'F8', 'F10'], axis = 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "eb3fcb74",
   "metadata": {},
   "outputs": [],
   "source": [
    "ds = df.values\n",
    "X = ds[:,0:4]\n",
    "y = ds[:,0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "598c261f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(700, 4)"
      ]
     },
     "execution_count": 34,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,random_state = 42)\n",
    "\n",
    "#res= clf._predict_proba_lr(X_test,Y_test)\n",
    "\n",
    "X_train.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "6eb21847",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Среднее значение\n",
    "mean = X_train.mean(axis=0)\n",
    "# Стандартное отклонение\n",
    "std = X_train.std(axis=0)\n",
    "X_train -= mean\n",
    "X_train /= std\n",
    "X_test -= mean\n",
    "X_test /= std"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "39519776",
   "metadata": {},
   "source": [
    "Создали сеть"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "4ab855b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = Sequential()\n",
    "model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))\n",
    "model.add(Dense(1))\n",
    "model.compile(optimizer='adam', loss='mse', metrics=['mae'])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f8cbbe5b",
   "metadata": {},
   "source": [
    "Обучаем"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "81c1e0cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/100\n",
      "700/700 - 1s - loss: 1.3281 - mae: 0.7501 - 837ms/epoch - 1ms/step\n",
      "Epoch 2/100\n",
      "700/700 - 1s - loss: 0.0383 - mae: 0.1501 - 503ms/epoch - 719us/step\n",
      "Epoch 3/100\n",
      "700/700 - 0s - loss: 0.0075 - mae: 0.0633 - 490ms/epoch - 699us/step\n",
      "Epoch 4/100\n",
      "700/700 - 0s - loss: 0.0037 - mae: 0.0456 - 481ms/epoch - 687us/step\n",
      "Epoch 5/100\n",
      "700/700 - 0s - loss: 0.0029 - mae: 0.0420 - 480ms/epoch - 686us/step\n",
      "Epoch 6/100\n",
      "700/700 - 0s - loss: 0.0022 - mae: 0.0361 - 483ms/epoch - 690us/step\n",
      "Epoch 7/100\n",
      "700/700 - 0s - loss: 0.0022 - mae: 0.0363 - 480ms/epoch - 686us/step\n",
      "Epoch 8/100\n",
      "700/700 - 0s - loss: 0.0019 - mae: 0.0331 - 483ms/epoch - 690us/step\n",
      "Epoch 9/100\n",
      "700/700 - 0s - loss: 0.0032 - mae: 0.0414 - 480ms/epoch - 685us/step\n",
      "Epoch 10/100\n",
      "700/700 - 0s - loss: 0.0016 - mae: 0.0303 - 482ms/epoch - 689us/step\n",
      "Epoch 11/100\n",
      "700/700 - 0s - loss: 0.0021 - mae: 0.0342 - 489ms/epoch - 699us/step\n",
      "Epoch 12/100\n",
      "700/700 - 0s - loss: 0.0029 - mae: 0.0391 - 485ms/epoch - 692us/step\n",
      "Epoch 13/100\n",
      "700/700 - 0s - loss: 0.0040 - mae: 0.0436 - 484ms/epoch - 691us/step\n",
      "Epoch 14/100\n",
      "700/700 - 0s - loss: 0.0012 - mae: 0.0268 - 483ms/epoch - 690us/step\n",
      "Epoch 15/100\n",
      "700/700 - 0s - loss: 0.0011 - mae: 0.0252 - 487ms/epoch - 696us/step\n",
      "Epoch 16/100\n",
      "700/700 - 0s - loss: 0.0023 - mae: 0.0362 - 479ms/epoch - 685us/step\n",
      "Epoch 17/100\n",
      "700/700 - 0s - loss: 0.0017 - mae: 0.0308 - 482ms/epoch - 688us/step\n",
      "Epoch 18/100\n",
      "700/700 - 0s - loss: 0.0021 - mae: 0.0316 - 485ms/epoch - 693us/step\n",
      "Epoch 19/100\n",
      "700/700 - 0s - loss: 0.0025 - mae: 0.0372 - 484ms/epoch - 691us/step\n",
      "Epoch 20/100\n",
      "700/700 - 1s - loss: 0.0014 - mae: 0.0272 - 519ms/epoch - 741us/step\n",
      "Epoch 21/100\n",
      "700/700 - 1s - loss: 0.0026 - mae: 0.0372 - 526ms/epoch - 751us/step\n",
      "Epoch 22/100\n",
      "700/700 - 1s - loss: 0.0010 - mae: 0.0243 - 581ms/epoch - 830us/step\n",
      "Epoch 23/100\n",
      "700/700 - 1s - loss: 0.0024 - mae: 0.0342 - 582ms/epoch - 831us/step\n",
      "Epoch 24/100\n",
      "700/700 - 1s - loss: 7.9887e-04 - mae: 0.0213 - 614ms/epoch - 877us/step\n",
      "Epoch 25/100\n",
      "700/700 - 1s - loss: 0.0011 - mae: 0.0247 - 595ms/epoch - 850us/step\n",
      "Epoch 26/100\n",
      "700/700 - 1s - loss: 0.0023 - mae: 0.0352 - 567ms/epoch - 810us/step\n",
      "Epoch 27/100\n",
      "700/700 - 1s - loss: 0.0016 - mae: 0.0282 - 572ms/epoch - 817us/step\n",
      "Epoch 28/100\n",
      "700/700 - 1s - loss: 0.0013 - mae: 0.0268 - 581ms/epoch - 830us/step\n",
      "Epoch 29/100\n",
      "700/700 - 1s - loss: 8.9450e-04 - mae: 0.0226 - 564ms/epoch - 806us/step\n",
      "Epoch 30/100\n",
      "700/700 - 1s - loss: 0.0013 - mae: 0.0256 - 558ms/epoch - 797us/step\n",
      "Epoch 31/100\n",
      "700/700 - 1s - loss: 0.0014 - mae: 0.0277 - 555ms/epoch - 793us/step\n",
      "Epoch 32/100\n",
      "700/700 - 1s - loss: 0.0014 - mae: 0.0280 - 527ms/epoch - 752us/step\n",
      "Epoch 33/100\n",
      "700/700 - 1s - loss: 0.0015 - mae: 0.0236 - 526ms/epoch - 751us/step\n",
      "Epoch 34/100\n",
      "700/700 - 1s - loss: 7.4283e-04 - mae: 0.0201 - 574ms/epoch - 820us/step\n",
      "Epoch 35/100\n",
      "700/700 - 1s - loss: 0.0018 - mae: 0.0303 - 533ms/epoch - 761us/step\n",
      "Epoch 36/100\n",
      "700/700 - 1s - loss: 7.1695e-04 - mae: 0.0199 - 541ms/epoch - 774us/step\n",
      "Epoch 37/100\n",
      "700/700 - 1s - loss: 8.7600e-04 - mae: 0.0208 - 533ms/epoch - 761us/step\n",
      "Epoch 38/100\n",
      "700/700 - 1s - loss: 0.0018 - mae: 0.0275 - 525ms/epoch - 750us/step\n",
      "Epoch 39/100\n",
      "700/700 - 1s - loss: 6.5176e-04 - mae: 0.0188 - 588ms/epoch - 839us/step\n",
      "Epoch 40/100\n",
      "700/700 - 1s - loss: 0.0012 - mae: 0.0259 - 583ms/epoch - 833us/step\n",
      "Epoch 41/100\n",
      "700/700 - 1s - loss: 0.0015 - mae: 0.0278 - 531ms/epoch - 759us/step\n",
      "Epoch 42/100\n",
      "700/700 - 1s - loss: 7.1734e-04 - mae: 0.0175 - 534ms/epoch - 763us/step\n",
      "Epoch 43/100\n",
      "700/700 - 1s - loss: 6.8882e-04 - mae: 0.0187 - 539ms/epoch - 770us/step\n",
      "Epoch 44/100\n",
      "700/700 - 1s - loss: 9.7367e-04 - mae: 0.0211 - 547ms/epoch - 781us/step\n",
      "Epoch 45/100\n",
      "700/700 - 1s - loss: 5.1202e-04 - mae: 0.0161 - 538ms/epoch - 769us/step\n",
      "Epoch 46/100\n",
      "700/700 - 1s - loss: 6.5135e-04 - mae: 0.0175 - 534ms/epoch - 763us/step\n",
      "Epoch 47/100\n",
      "700/700 - 1s - loss: 0.0020 - mae: 0.0296 - 528ms/epoch - 754us/step\n",
      "Epoch 48/100\n",
      "700/700 - 1s - loss: 5.0193e-04 - mae: 0.0151 - 542ms/epoch - 774us/step\n",
      "Epoch 49/100\n",
      "700/700 - 1s - loss: 6.3949e-04 - mae: 0.0189 - 534ms/epoch - 763us/step\n",
      "Epoch 50/100\n",
      "700/700 - 1s - loss: 8.6189e-04 - mae: 0.0198 - 584ms/epoch - 834us/step\n",
      "Epoch 51/100\n",
      "700/700 - 1s - loss: 4.8984e-04 - mae: 0.0156 - 564ms/epoch - 806us/step\n",
      "Epoch 52/100\n",
      "700/700 - 1s - loss: 7.4903e-04 - mae: 0.0201 - 531ms/epoch - 758us/step\n",
      "Epoch 53/100\n",
      "700/700 - 1s - loss: 0.0011 - mae: 0.0247 - 528ms/epoch - 754us/step\n",
      "Epoch 54/100\n",
      "700/700 - 1s - loss: 1.8660e-04 - mae: 0.0092 - 528ms/epoch - 754us/step\n",
      "Epoch 55/100\n",
      "700/700 - 1s - loss: 7.0828e-04 - mae: 0.0165 - 523ms/epoch - 747us/step\n",
      "Epoch 56/100\n",
      "700/700 - 1s - loss: 4.3613e-04 - mae: 0.0147 - 528ms/epoch - 754us/step\n",
      "Epoch 57/100\n",
      "700/700 - 1s - loss: 0.0011 - mae: 0.0194 - 525ms/epoch - 750us/step\n",
      "Epoch 58/100\n",
      "700/700 - 1s - loss: 1.9949e-04 - mae: 0.0105 - 534ms/epoch - 762us/step\n",
      "Epoch 59/100\n",
      "700/700 - 1s - loss: 0.0017 - mae: 0.0281 - 533ms/epoch - 761us/step\n",
      "Epoch 60/100\n",
      "700/700 - 1s - loss: 2.1884e-04 - mae: 0.0094 - 576ms/epoch - 822us/step\n",
      "Epoch 61/100\n",
      "700/700 - 1s - loss: 4.7380e-04 - mae: 0.0160 - 519ms/epoch - 741us/step\n",
      "Epoch 62/100\n",
      "700/700 - 1s - loss: 6.0317e-04 - mae: 0.0173 - 600ms/epoch - 857us/step\n",
      "Epoch 63/100\n",
      "700/700 - 1s - loss: 3.9800e-04 - mae: 0.0142 - 544ms/epoch - 777us/step\n",
      "Epoch 64/100\n",
      "700/700 - 1s - loss: 0.0014 - mae: 0.0235 - 563ms/epoch - 804us/step\n",
      "Epoch 65/100\n",
      "700/700 - 1s - loss: 1.5463e-04 - mae: 0.0083 - 533ms/epoch - 761us/step\n",
      "Epoch 66/100\n",
      "700/700 - 1s - loss: 6.6222e-04 - mae: 0.0170 - 582ms/epoch - 832us/step\n",
      "Epoch 67/100\n",
      "700/700 - 1s - loss: 6.8747e-04 - mae: 0.0181 - 583ms/epoch - 833us/step\n",
      "Epoch 68/100\n",
      "700/700 - 1s - loss: 2.9161e-04 - mae: 0.0119 - 527ms/epoch - 753us/step\n",
      "Epoch 69/100\n",
      "700/700 - 1s - loss: 6.2240e-04 - mae: 0.0167 - 524ms/epoch - 748us/step\n",
      "Epoch 70/100\n",
      "700/700 - 1s - loss: 6.6377e-04 - mae: 0.0167 - 544ms/epoch - 777us/step\n",
      "Epoch 71/100\n",
      "700/700 - 1s - loss: 1.5750e-04 - mae: 0.0079 - 577ms/epoch - 824us/step\n",
      "Epoch 72/100\n",
      "700/700 - 1s - loss: 8.0239e-04 - mae: 0.0187 - 572ms/epoch - 817us/step\n",
      "Epoch 73/100\n",
      "700/700 - 1s - loss: 2.7004e-04 - mae: 0.0112 - 571ms/epoch - 815us/step\n",
      "Epoch 74/100\n",
      "700/700 - 1s - loss: 6.9477e-04 - mae: 0.0155 - 574ms/epoch - 820us/step\n",
      "Epoch 75/100\n",
      "700/700 - 1s - loss: 7.3573e-04 - mae: 0.0176 - 553ms/epoch - 790us/step\n",
      "Epoch 76/100\n",
      "700/700 - 1s - loss: 1.7783e-04 - mae: 0.0093 - 575ms/epoch - 821us/step\n",
      "Epoch 77/100\n",
      "700/700 - 1s - loss: 4.7711e-04 - mae: 0.0155 - 527ms/epoch - 752us/step\n",
      "Epoch 78/100\n",
      "700/700 - 1s - loss: 3.1328e-04 - mae: 0.0126 - 531ms/epoch - 759us/step\n",
      "Epoch 79/100\n",
      "700/700 - 1s - loss: 5.8979e-04 - mae: 0.0158 - 531ms/epoch - 758us/step\n",
      "Epoch 80/100\n",
      "700/700 - 1s - loss: 5.2508e-04 - mae: 0.0145 - 578ms/epoch - 826us/step\n",
      "Epoch 81/100\n",
      "700/700 - 1s - loss: 3.0756e-04 - mae: 0.0114 - 564ms/epoch - 806us/step\n",
      "Epoch 82/100\n",
      "700/700 - 1s - loss: 2.8803e-04 - mae: 0.0118 - 527ms/epoch - 752us/step\n",
      "Epoch 83/100\n",
      "700/700 - 1s - loss: 1.7837e-04 - mae: 0.0094 - 573ms/epoch - 819us/step\n",
      "Epoch 84/100\n",
      "700/700 - 1s - loss: 7.3112e-04 - mae: 0.0190 - 524ms/epoch - 748us/step\n",
      "Epoch 85/100\n",
      "700/700 - 1s - loss: 5.0155e-04 - mae: 0.0164 - 525ms/epoch - 750us/step\n",
      "Epoch 86/100\n",
      "700/700 - 1s - loss: 7.4446e-05 - mae: 0.0064 - 534ms/epoch - 763us/step\n",
      "Epoch 87/100\n",
      "700/700 - 1s - loss: 8.3623e-04 - mae: 0.0167 - 547ms/epoch - 781us/step\n",
      "Epoch 88/100\n",
      "700/700 - 1s - loss: 6.6759e-05 - mae: 0.0059 - 522ms/epoch - 746us/step\n",
      "Epoch 89/100\n",
      "700/700 - 1s - loss: 7.8437e-04 - mae: 0.0184 - 535ms/epoch - 764us/step\n",
      "Epoch 90/100\n",
      "700/700 - 1s - loss: 1.4448e-04 - mae: 0.0082 - 574ms/epoch - 820us/step\n",
      "Epoch 91/100\n",
      "700/700 - 1s - loss: 2.7724e-04 - mae: 0.0124 - 543ms/epoch - 776us/step\n",
      "Epoch 92/100\n",
      "700/700 - 1s - loss: 4.8082e-04 - mae: 0.0141 - 563ms/epoch - 804us/step\n",
      "Epoch 93/100\n",
      "700/700 - 1s - loss: 0.0013 - mae: 0.0176 - 542ms/epoch - 774us/step\n",
      "Epoch 94/100\n",
      "700/700 - 1s - loss: 3.3377e-05 - mae: 0.0042 - 536ms/epoch - 765us/step\n",
      "Epoch 95/100\n",
      "700/700 - 1s - loss: 5.0530e-04 - mae: 0.0156 - 533ms/epoch - 761us/step\n",
      "Epoch 96/100\n",
      "700/700 - 1s - loss: 1.8501e-04 - mae: 0.0095 - 529ms/epoch - 755us/step\n",
      "Epoch 97/100\n",
      "700/700 - 1s - loss: 0.0012 - mae: 0.0208 - 559ms/epoch - 798us/step\n",
      "Epoch 98/100\n",
      "700/700 - 1s - loss: 1.0334e-04 - mae: 0.0073 - 611ms/epoch - 872us/step\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 99/100\n",
      "700/700 - 1s - loss: 1.5674e-04 - mae: 0.0061 - 574ms/epoch - 820us/step\n",
      "Epoch 100/100\n",
      "700/700 - 1s - loss: 3.3270e-04 - mae: 0.0123 - 576ms/epoch - 823us/step\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<keras.callbacks.History at 0x1faabbc71c0>"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "328d2d87",
   "metadata": {},
   "source": [
    "Оценка точности работы сети"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "9f7b6084",
   "metadata": {},
   "outputs": [],
   "source": [
    "mse, mae = model.evaluate(X_test, y_test, verbose=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "2bdffd74",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Средняя абсолютная ошибка (ед.): 0.011121131479740143\n"
     ]
    }
   ],
   "source": [
    "print(\"Средняя абсолютная ошибка (ед.):\", mae)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4870464b",
   "metadata": {},
   "source": [
    "Использование сети для предсказания соотношения"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "15acd0d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "pred = model.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "77d94fb4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Предсказанное соотношение: 1.8682741 , правильное соотношение: 1.85729150266508\n"
     ]
    }
   ],
   "source": [
    "print(\"Предсказанное соотношение:\", pred[1][0], \", правильное соотношение:\", y_test[1])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6f0b1ee3",
   "metadata": {},
   "source": [
    "1. Базовая модель"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e6d707c7",
   "metadata": {},
   "source": [
    "Оболочкам Keras требуется функция в качестве аргумента. Эта функция, которую мы должны определить, отвечает за создание модели нейронной сети для оценки.\n",
    "\n",
    "Ниже мы определяем функцию для создания базовой модели для оценки. Это простая модель, которая имеет один полностью связанный скрытый слой с тем же количеством нейронов, что и входные атрибуты (13). В сети используются полезные практики, такие как функция активации выпрямителя для скрытого слоя. Для выходного слоя функция активации не используется, поскольку это проблема регрессии, и мы заинтересованы в прогнозировании числовых значений напрямую без преобразования.\n",
    "\n",
    "Используется эффективный алгоритм оптимизации ADAM и оптимизируется функция потери среднего квадрата ошибки. Это будет та же метрика, которую мы будем использовать для оценки производительности модели. Это желательный показатель, потому что получение квадратного корня дает нам значение ошибки, которое мы можем непосредственно понять в контексте проблемы"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "05f4b458",
   "metadata": {},
   "outputs": [],
   "source": [
    "# define base model\n",
    "def baseline_model():\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(1, kernel_initializer='normal'))\n",
    "    # Compile model\n",
    "    model.compile(loss='mean_squared_error', optimizer='adam')\n",
    "    return model"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0f9076b8",
   "metadata": {},
   "source": [
    "Объект оболочки Keras для использования в scikit-learn в качестве регрессионной оценки называется KerasRegressor. Мы создаем экземпляр и передаем ему как имя функции для создания модели нейронной сети, так и некоторые параметры для передачи функции fit () модели позже, например, количество эпох и размер пакета. Оба из них установлены на разумные значения по умолчанию.\n",
    "\n",
    "Мы также инициализируем генератор случайных чисел с постоянным случайным начальным числом, процесс, который мы будем повторять для каждой модели, оцененной в этом руководстве. Это попытка обеспечить последовательное сравнение моделей."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "bc66d18b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# fix random seed for reproducibility\n",
    "seed = 7\n",
    "numpy.random.seed(seed)\n",
    "# evaluate model with standardized dataset\n",
    "estimator = KerasRegressor(build_fn = baseline_model, epochs=100, batch_size=5, verbose=0)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "85332e91",
   "metadata": {},
   "source": [
    "Последний шаг - оценить эту базовую модель. Мы будем использовать 10-кратную перекрестную проверку для оценки модели."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "392cae49",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09e02862",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b696847",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a8b6b50",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "bfd603b9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Results: nan (nan) MSE\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:372: FitFailedWarning: \n",
      "10 fits failed out of a total of 10.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_30\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_31\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_32\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_33\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_34\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_35\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_36\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_37\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_38\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_39\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "kfold = KFold(n_splits=10, shuffle=True, random_state=seed)\n",
    "results = cross_val_score(estimator, X, Y, cv=kfold)\n",
    "print(\"Results: %.2f (%.2f) MSE\" % (results.mean(), results.std()))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "80695250",
   "metadata": {},
   "source": [
    "ыполнение этого кода дает нам оценку производительности модели по проблеме для невидимых данных. В результате сообщается о среднем квадрате ошибки, включая среднее и стандартное отклонение (среднее отклонение) по всем 10-кратным оценкам перекрестной проверки."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "718bd679",
   "metadata": {},
   "source": [
    "2. Стандартизированный набор"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "40f1b63c",
   "metadata": {},
   "source": [
    "Важной проблемой, связанной с набором данных, является то, что все входные атрибуты различаются по своим масштабам, поскольку они измеряют различные количества.\n",
    "\n",
    "Практически всегда полезно подготовить данные перед их моделированием с использованием модели нейронной сети.\n",
    "\n",
    "Продолжая вышеприведенную базовую модель, мы можем переоценить ту же модель, используя стандартизированную версию входного набора данных.\n",
    "\n",
    "Мы можем использовать Scikit-Learn для выполнения стандартизации во время процесса оценки модели, в пределах каждого раза перекрестной проверки. Это гарантирует отсутствие утечки данных из каждого перекрестного валидационного набора тестов в обучающие данные.\n",
    "\n",
    "Приведенный ниже код создает конвейер scikit-learn, который сначала стандартизирует набор данных, а затем создает и оценивает базовую модель нейронной сети."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "52ef914d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Standardized: nan (nan) MSE\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:372: FitFailedWarning: \n",
      "10 fits failed out of a total of 10.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_40\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_41\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_42\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_43\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_44\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_45\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_46\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_47\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_48\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 742, in fit\n",
      "    self._fit(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 911, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\scikeras\\wrappers.py\", line 515, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1147, in autograph_handler\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 67, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\nat_n\\anaconda3\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 264, in assert_input_compatibility\n",
      "        raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_49\" is incompatible with the layer: expected shape=(None, 13), found shape=(5, 12)\n",
      "\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "# evaluate model with standardized dataset\n",
    "numpy.random.seed(seed)\n",
    "estimators = []\n",
    "estimators.append(('standardize', StandardScaler()))\n",
    "estimators.append(('mlp', KerasRegressor(build_fn=baseline_model, epochs=50, batch_size=5, verbose=0)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = KFold(n_splits=10, shuffle = True, random_state=seed)\n",
    "results = cross_val_score(pipeline, X, Y, cv=kfold)\n",
    "print(\"Standardized: %.2f (%.2f) MSE\" % (results.mean(), results.std()))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "11983c6c",
   "metadata": {},
   "source": [
    "Выполнение примера обеспечивает улучшенную производительность по сравнению с базовой моделью без стандартизированных данных, исключая ошибку."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9c4561c7",
   "metadata": {},
   "source": [
    "Еще одним расширением этого раздела будет аналогичное применение масштабирования к выходной переменной, например, его нормализация в диапазоне 0-1, и использование сигмоидальной или аналогичной функции активации на выходном слое для сужения выходных прогнозов в том же диапазоне."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7602afbb",
   "metadata": {},
   "source": [
    "3. настройка топологии сети"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "106112a1",
   "metadata": {},
   "source": [
    "Есть много проблем, которые могут быть оптимизированы для модели нейронной сети.\n",
    "\n",
    "Возможно, точка наибольшего влияния - это структура самой сети, в том числе количество слоев и количество нейронов в каждом слое.\n",
    "\n",
    "В этом разделе мы рассмотрим две дополнительные топологии сети в целях дальнейшего повышения производительности модели. Мы рассмотрим как более глубокую, так и более широкую топологию сети."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cdebb7a2",
   "metadata": {},
   "source": [
    "Оценить более глубокую топологию сети"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "08abd637",
   "metadata": {},
   "source": [
    "Один из способов повысить производительность нейронной сети - добавить больше слоев. Это может позволить модели извлекать и рекомбинировать функции высшего порядка, встроенные в данные.\n",
    "\n",
    "В этом разделе мы оценим эффект от добавления еще одного скрытого слоя к модели. Это так же просто, как определить новую функцию, которая создаст эту более глубокую модель, скопированную из нашей базовой модели выше. Затем мы можем вставить новую строку после первого скрытого слоя. В этом случае около половины числа нейронов."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "c915f66a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# define the model\n",
    "def larger_model():\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(6, kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(1, kernel_initializer='normal'))\n",
    "    # Compile model\n",
    "    model.compile(loss='mean_squared_error', optimizer='adam')\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7cc4f4f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b45c228",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "351aa6a4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "a59ca010",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(700, 12)"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X, y = df.drop(['T1'], axis = 1).values, df['T1'].values\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,random_state = 42)\n",
    "\n",
    "#res= clf._predict_proba_lr(X_test,Y_test)\n",
    "\n",
    "X_train.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "579d956f",
   "metadata": {},
   "source": [
    "2. Разрабатываем базовую модель"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "23b67957",
   "metadata": {},
   "source": [
    "Строим простую полносвязную нейронную сеть (feed forward neural network). Выходной слой с одним линейным нейроном — для задачи регрессии. Функция активации — RELU в промежуточном слое и sigmoid в выходном."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "e180d59d",
   "metadata": {},
   "outputs": [],
   "source": [
    "normalizer = tf.keras.layers.Normalization(axis=-1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "f7c851cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_norm = normalizer.adapt(np.array(X_train))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "27ed5db2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_5\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " dense_4 (Dense)             (None, 12)                84        \n",
      "                                                                 \n",
      " dense_5 (Dense)             (None, 12)                156       \n",
      "                                                                 \n",
      " dense_6 (Dense)             (None, 6)                 78        \n",
      "                                                                 \n",
      " dense_7 (Dense)             (None, 1)                 7         \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 325\n",
      "Trainable params: 325\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model = Sequential([\n",
    "    Dense(12, activation='relu', input_dim=6),\n",
    "    Dense(12, activation='relu'),\n",
    "    Dense(6, activation='relu'),\n",
    "    Dense(1, activation='sigmoid'),\n",
    "])\n",
    "\n",
    "model.compile(optimizer='adam', \n",
    "              #loss='binary_crossentropy',  # только для задач классификации\n",
    "              metrics=['accuracy', 'mse', 'mae'])  # только для задач классификации\n",
    "\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "0f90f972",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Failed to find data adapter that can handle input: <class 'NoneType'>, <class 'numpy.ndarray'>",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_816/3049679001.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX_train_norm\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbatch_size\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m32\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mepochs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m10\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     65\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m  \u001b[1;31m# pylint: disable=broad-except\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 67\u001b[1;33m       \u001b[1;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     68\u001b[0m     \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     69\u001b[0m       \u001b[1;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\keras\\engine\\data_adapter.py\u001b[0m in \u001b[0;36mselect_data_adapter\u001b[1;34m(x, y)\u001b[0m\n\u001b[0;32m    982\u001b[0m   \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0madapter_cls\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    983\u001b[0m     \u001b[1;31m# TODO(scottzhu): This should be a less implementation-specific error.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 984\u001b[1;33m     raise ValueError(\n\u001b[0m\u001b[0;32m    985\u001b[0m         \u001b[1;34m\"Failed to find data adapter that can handle \"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    986\u001b[0m         \"input: {}, {}\".format(\n",
      "\u001b[1;31mValueError\u001b[0m: Failed to find data adapter that can handle input: <class 'NoneType'>, <class 'numpy.ndarray'>"
     ]
    }
   ],
   "source": [
    "model.fit(X_train_norm, y_train, batch_size=32, epochs=10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "2e90e1a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "model.compile(\n",
    "    optimizer=tf.optimizers.SGD(learning_rate=0.01, momentum=0.9, nesterov=False),\n",
    "    loss='mean_absolute_error')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "ef6533b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/40\n",
      "9/9 [==============================] - 3s 47ms/step - loss: 2.3977 - val_loss: 3.7731\n",
      "Epoch 2/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 1.5106 - val_loss: 3.3948\n",
      "Epoch 3/40\n",
      "9/9 [==============================] - 0s 10ms/step - loss: 1.0691 - val_loss: 4.4235\n",
      "Epoch 4/40\n",
      "9/9 [==============================] - 0s 10ms/step - loss: 0.8015 - val_loss: 6.4204\n",
      "Epoch 5/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.7488 - val_loss: 1.5774\n",
      "Epoch 6/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.7265 - val_loss: 1.5490\n",
      "Epoch 7/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.7225 - val_loss: 0.9193\n",
      "Epoch 8/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.7095 - val_loss: 0.8876\n",
      "Epoch 9/40\n",
      "9/9 [==============================] - 0s 14ms/step - loss: 0.7068 - val_loss: 0.8837\n",
      "Epoch 10/40\n",
      "9/9 [==============================] - 0s 10ms/step - loss: 0.7122 - val_loss: 0.8817\n",
      "Epoch 11/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6980 - val_loss: 0.8190\n",
      "Epoch 12/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.7028 - val_loss: 0.8546\n",
      "Epoch 13/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.7060 - val_loss: 0.7990\n",
      "Epoch 14/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.6925 - val_loss: 0.8174\n",
      "Epoch 15/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.6795 - val_loss: 0.7763\n",
      "Epoch 16/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6964 - val_loss: 0.8134\n",
      "Epoch 17/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6819 - val_loss: 0.7878\n",
      "Epoch 18/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6714 - val_loss: 0.7662\n",
      "Epoch 19/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.6704 - val_loss: 0.8286\n",
      "Epoch 20/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.6784 - val_loss: 0.8146\n",
      "Epoch 21/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6723 - val_loss: 0.8082\n",
      "Epoch 22/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6749 - val_loss: 0.7875\n",
      "Epoch 23/40\n",
      "9/9 [==============================] - 0s 10ms/step - loss: 0.6595 - val_loss: 0.8467\n",
      "Epoch 24/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6598 - val_loss: 0.7996\n",
      "Epoch 25/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.6619 - val_loss: 0.8394\n",
      "Epoch 26/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6702 - val_loss: 0.8394\n",
      "Epoch 27/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.6685 - val_loss: 0.9365\n",
      "Epoch 28/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6718 - val_loss: 0.8814\n",
      "Epoch 29/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6748 - val_loss: 0.7633\n",
      "Epoch 30/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6670 - val_loss: 0.7959\n",
      "Epoch 31/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6506 - val_loss: 0.7866\n",
      "Epoch 32/40\n",
      "9/9 [==============================] - 0s 14ms/step - loss: 0.6517 - val_loss: 0.7987\n",
      "Epoch 33/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6395 - val_loss: 0.9082\n",
      "Epoch 34/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6468 - val_loss: 0.7491\n",
      "Epoch 35/40\n",
      "9/9 [==============================] - 0s 12ms/step - loss: 0.6582 - val_loss: 0.8345\n",
      "Epoch 36/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6582 - val_loss: 0.8037\n",
      "Epoch 37/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6423 - val_loss: 0.7888\n",
      "Epoch 38/40\n",
      "9/9 [==============================] - 0s 9ms/step - loss: 0.6315 - val_loss: 0.8040\n",
      "Epoch 39/40\n",
      "9/9 [==============================] - 0s 11ms/step - loss: 0.6306 - val_loss: 0.8523\n",
      "Epoch 40/40\n",
      "9/9 [==============================] - 0s 13ms/step - loss: 0.6317 - val_loss: 0.8225\n",
      "Wall time: 6.71 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "history = model.fit(\n",
    "    X_train,\n",
    "    y_train,\n",
    "    batch_size = 64,\n",
    "    epochs=40,\n",
    "    verbose=1,\n",
    "    validation_split = 0.2\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "df20ee78",
   "metadata": {},
   "outputs": [],
   "source": [
    "value = [[x for x in range(0,5)],\n",
    "         [x for x in range(10,15)],\n",
    "         [x for x in range(20,25)]] "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "id": "cfe40718",
   "metadata": {},
   "outputs": [],
   "source": [
    "value = np.array(value)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "id": "b37917b8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Numpy array: [[ 0  1  2  3  4]\n",
      " [10 11 12 13 14]\n",
      " [20 21 22 23 24]]\n",
      "Mean: [10. 11. 12. 13. 14.]\n"
     ]
    }
   ],
   "source": [
    "print(\"Numpy array:\", value)\n",
    "sum = value.sum(axis=0)  \n",
    "print(\"Mean:\", sum / value.shape[0])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b70ecbad",
   "metadata": {},
   "source": [
    "Сначала суммируем по строкам. Для этого указываем axis=0. Если указать axis = 1, то суммирование будет проходить по столбцам, а это нам не нужно. После того, как просуммировали, делим на общее количество записей, которое получаем через: value.shape[0].\\\n",
    "В numpy array есть стандартный метод для определения среднего арифметического «mean»:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "id": "2c03daf7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mean:\r\n",
      " [10. 11. 12. 13. 14.]\n"
     ]
    }
   ],
   "source": [
    "mean = value.mean(axis=0) #Вычисляем среднее по строкам\n",
    "print(\"Mean:\\r\\n\", mean)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "id": "0fd4b3c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "mean = X_train.mean(axis=0)\n",
    "X_train -= mean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "id": "e669c007",
   "metadata": {},
   "outputs": [],
   "source": [
    "std = X_train.std(axis=0)\n",
    "X_train /= std"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "id": "d16feb1a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def norm(x):\n",
    "  return (x - mean) / std\n",
    "X_train = norm(X_train);\n",
    "X_test = norm(X_test);"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7d30cbea",
   "metadata": {},
   "source": [
    "Поскольку функция активации sigmoid на выходе работает от 0 до 1, то сделаем нормировку для правильных ответов y_train. Для этого опустим минимальные значения к 0, вычтя из данных минимальное значение обучающей выборки.\n",
    "\n",
    "Чтобы привести величины в выборке к 1, разделим данные на значение амплитуды взятое от новой (смещенной) выборки. Сохраняем минимальные и максимальные значения, поскольку после получения результатов на выходе сети нужно будет выполнить обратную процедуру.\n",
    "\n",
    "При корректировке данных тестовой выборки воспользуемся полученным максимальным значением амплитуды от обучающей выборки:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "24052ff8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Приводим значения ответов в диапазон от 0 до 1\n",
    "min_y = y_train.min()\n",
    "max_y = y_train.max() - min_y #\"опустим\" максимум на min_y\n",
    "y_train = (y_train - min_y) / max_y #отклонение от минимума к амплитуде\n",
    "y_test = (y_test - min_y) / max_y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "id": "5d8f412c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.0\n",
      "1.0\n"
     ]
    }
   ],
   "source": [
    "print(y_train.min())\n",
    "print(y_train.max())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "id": "d525f53f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[-27.60107436  -2.27876103  -3.9423946   -8.62246026  -6.83050469\n",
      "  -1.71495688 -23.67683355  -5.02899521  -3.74669254   0.9832866\n",
      "  -2.17441362  -4.41142583]\n",
      "0.6295456749035943\n"
     ]
    }
   ],
   "source": [
    "# Нормированные данные\n",
    "print(X_train[0])\n",
    "print(y_train[0])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4e894475",
   "metadata": {},
   "source": [
    "Строим простую полносвязную нейронную сеть (feed forward neural network). Выходной слой с одним линейным нейроном — для задачи регрессии. Функция активации — RELU в промежуточном слое и sigmoid в выходном. Конфигурация сети взята из хорошего примера"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "1a90fc9e",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'shape'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_816/3673094380.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0mmodel\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mSequential\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0madd\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mDense\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m64\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mactivation\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'relu'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0minput_shape\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX_train_norm\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0madd\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mDense\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m64\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mactivation\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'relu'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0madd\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mDense\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mactivation\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'sigmoid'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;31m# sigmoid, т.к. данные от 0 до 1\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'shape'"
     ]
    }
   ],
   "source": [
    "model = Sequential()\n",
    "model.add(Dense(64, activation='relu', input_shape=(X_train_norm.shape[1],)))\n",
    "model.add(Dense(64, activation='relu'))\n",
    "model.add(Dense(1, activation='sigmoid')) # sigmoid, т.к. данные от 0 до 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "ce565826",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_3\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " dense_15 (Dense)            (None, 64)                832       \n",
      "                                                                 \n",
      " dense_16 (Dense)            (None, 64)                4160      \n",
      "                                                                 \n",
      " dense_17 (Dense)            (None, 1)                 65        \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 5,057\n",
      "Trainable params: 5,057\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "print(model.summary()) # архитектура нашей модели"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "id": "ef846aee",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Т.к. задача регрессии, удобнее использовать mean square error(средне-квадратичная ошибка).\n",
    "# В качестве метрики берем mean absolute error (средний модуль ошибки)\n",
    "model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "4d948987",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "21/21 [==============================] - 1s 14ms/step - loss: 0.0895 - mae: 0.2450 - val_loss: 0.1309 - val_mae: 0.3213\n",
      "Epoch 2/5\n",
      "21/21 [==============================] - 0s 6ms/step - loss: 0.0544 - mae: 0.1870 - val_loss: 0.0470 - val_mae: 0.1862\n",
      "Epoch 3/5\n",
      "21/21 [==============================] - 0s 6ms/step - loss: 0.0470 - mae: 0.1703 - val_loss: 0.0429 - val_mae: 0.1620\n",
      "Epoch 4/5\n",
      "21/21 [==============================] - 0s 6ms/step - loss: 0.0527 - mae: 0.1863 - val_loss: 0.0900 - val_mae: 0.2644\n",
      "Epoch 5/5\n",
      "21/21 [==============================] - 0s 5ms/step - loss: 0.0517 - mae: 0.1833 - val_loss: 0.0383 - val_mae: 0.1657\n"
     ]
    }
   ],
   "source": [
    "history = model.fit(X_train, \n",
    "                    y_train, \n",
    "                    epochs=5, \n",
    "                    validation_split=0.1, \n",
    "                    verbose=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "4fe1a60a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Делаем прогноз. Возвращается копия предсказания в виде одномерного массива\n",
    "pred = model.predict(X_test).flatten() \n",
    "\n",
    "# Возвращаем к прежнему размеру\n",
    "pred = pred * max_y + min_y \n",
    "y_test = y_test * max_y + min_y\n",
    "\n",
    "# Возвращаем к прежнему размеру\n",
    "#pred = pred * (max_y - min_y) + min_y \n",
    "#y_test = y_test * (max_y - min_y) + min_y\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "1a81883e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.8140637800712206\n"
     ]
    }
   ],
   "source": [
    "# Средний модуль отклонения \n",
    "err = np.mean(abs(pred - y_test))\n",
    "print(err)\n",
    "#print(len(pred))\n",
    "\n",
    "#err = sum(abs(pred - y_test)) / len(pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "20a46787",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.8140637800712206\n"
     ]
    }
   ],
   "source": [
    "print(err)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "e7e9d45b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2.9514584546978684\n"
     ]
    }
   ],
   "source": [
    "# Средняя цена по выборке\n",
    "print(np.mean(y_test))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "id": "436349f0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Сеть сказала:  2.68 , а верный ответ:  3.79 , разница:  -1.11\n",
      "Сеть сказала:  2.81 , а верный ответ:  2.66 , разница:  0.15\n",
      "Сеть сказала:  2.85 , а верный ответ:  3.17 , разница:  -0.32\n",
      "Сеть сказала:  2.92 , а верный ответ:  1.77 , разница:  1.15\n",
      "Сеть сказала:  3.29 , а верный ответ:  3.28 , разница:  0.02\n",
      "Сеть сказала:  3.27 , а верный ответ:  3.52 , разница:  -0.25\n",
      "Сеть сказала:  2.89 , а верный ответ:  3.5 , разница:  -0.61\n",
      "Сеть сказала:  2.67 , а верный ответ:  2.55 , разница:  0.12\n",
      "Сеть сказала:  3.13 , а верный ответ:  1.94 , разница:  1.19\n",
      "Сеть сказала:  3.04 , а верный ответ:  2.01 , разница:  1.03\n",
      "Сеть сказала:  3.12 , а верный ответ:  2.8 , разница:  0.31\n",
      "Сеть сказала:  2.5 , а верный ответ:  3.73 , разница:  -1.23\n",
      "Сеть сказала:  3.43 , а верный ответ:  1.61 , разница:  1.82\n",
      "Сеть сказала:  2.95 , а верный ответ:  3.11 , разница:  -0.15\n",
      "Сеть сказала:  2.75 , а верный ответ:  2.13 , разница:  0.62\n",
      "Сеть сказала:  2.99 , а верный ответ:  2.63 , разница:  0.36\n",
      "Сеть сказала:  2.92 , а верный ответ:  3.68 , разница:  -0.76\n",
      "Сеть сказала:  2.89 , а верный ответ:  3.87 , разница:  -0.97\n",
      "Сеть сказала:  2.74 , а верный ответ:  3.56 , разница:  -0.83\n",
      "Сеть сказала:  3.2 , а верный ответ:  4.45 , разница:  -1.24\n",
      "Сеть сказала:  3.22 , а верный ответ:  2.61 , разница:  0.61\n",
      "Сеть сказала:  2.7 , а верный ответ:  2.43 , разница:  0.27\n",
      "Сеть сказала:  3.04 , а верный ответ:  3.9 , разница:  -0.86\n",
      "Сеть сказала:  2.95 , а верный ответ:  3.8 , разница:  -0.85\n",
      "Сеть сказала:  2.95 , а верный ответ:  1.52 , разница:  1.42\n",
      "Сеть сказала:  2.79 , а верный ответ:  1.74 , разница:  1.05\n",
      "Сеть сказала:  2.72 , а верный ответ:  3.28 , разница:  -0.56\n",
      "Сеть сказала:  3.0 , а верный ответ:  2.46 , разница:  0.53\n",
      "Сеть сказала:  2.81 , а верный ответ:  1.89 , разница:  0.93\n",
      "Сеть сказала:  3.28 , а верный ответ:  4.34 , разница:  -1.06\n",
      "Сеть сказала:  2.49 , а верный ответ:  1.65 , разница:  0.84\n",
      "Сеть сказала:  2.76 , а верный ответ:  3.69 , разница:  -0.94\n",
      "Сеть сказала:  2.2 , а верный ответ:  2.2 , разница:  -0.0\n",
      "Сеть сказала:  3.18 , а верный ответ:  3.31 , разница:  -0.13\n",
      "Сеть сказала:  2.95 , а верный ответ:  1.27 , разница:  1.68\n",
      "Сеть сказала:  2.84 , а верный ответ:  2.98 , разница:  -0.14\n",
      "Сеть сказала:  2.95 , а верный ответ:  3.02 , разница:  -0.07\n",
      "Сеть сказала:  2.82 , а верный ответ:  1.58 , разница:  1.23\n",
      "Сеть сказала:  2.94 , а верный ответ:  2.22 , разница:  0.72\n",
      "Сеть сказала:  2.92 , а верный ответ:  3.91 , разница:  -0.99\n",
      "Сеть сказала:  2.84 , а верный ответ:  4.24 , разница:  -1.4\n",
      "Сеть сказала:  2.15 , а верный ответ:  2.98 , разница:  -0.83\n",
      "Сеть сказала:  2.58 , а верный ответ:  4.23 , разница:  -1.65\n",
      "Сеть сказала:  3.03 , а верный ответ:  2.05 , разница:  0.98\n",
      "Сеть сказала:  2.89 , а верный ответ:  1.75 , разница:  1.14\n",
      "Сеть сказала:  3.02 , а верный ответ:  3.38 , разница:  -0.36\n",
      "Сеть сказала:  2.49 , а верный ответ:  2.81 , разница:  -0.31\n",
      "Сеть сказала:  3.07 , а верный ответ:  2.86 , разница:  0.2\n",
      "Сеть сказала:  3.13 , а верный ответ:  2.71 , разница:  0.43\n",
      "Сеть сказала:  2.52 , а верный ответ:  2.02 , разница:  0.51\n",
      "Сеть сказала:  3.63 , а верный ответ:  3.86 , разница:  -0.23\n",
      "Сеть сказала:  3.5 , а верный ответ:  2.98 , разница:  0.52\n",
      "Сеть сказала:  3.17 , а верный ответ:  3.12 , разница:  0.06\n",
      "Сеть сказала:  3.12 , а верный ответ:  4.55 , разница:  -1.43\n",
      "Сеть сказала:  2.72 , а верный ответ:  3.11 , разница:  -0.39\n",
      "Сеть сказала:  1.84 , а верный ответ:  2.92 , разница:  -1.08\n",
      "Сеть сказала:  2.64 , а верный ответ:  5.59 , разница:  -2.96\n",
      "Сеть сказала:  3.27 , а верный ответ:  2.69 , разница:  0.58\n",
      "Сеть сказала:  3.21 , а верный ответ:  2.81 , разница:  0.4\n",
      "Сеть сказала:  3.27 , а верный ответ:  1.04 , разница:  2.23\n",
      "Сеть сказала:  2.41 , а верный ответ:  3.0 , разница:  -0.59\n",
      "Сеть сказала:  2.94 , а верный ответ:  2.69 , разница:  0.25\n",
      "Сеть сказала:  3.55 , а верный ответ:  2.44 , разница:  1.11\n",
      "Сеть сказала:  2.26 , а верный ответ:  2.86 , разница:  -0.61\n",
      "Сеть сказала:  3.44 , а верный ответ:  4.8 , разница:  -1.37\n",
      "Сеть сказала:  2.44 , а верный ответ:  1.98 , разница:  0.46\n",
      "Сеть сказала:  3.12 , а верный ответ:  2.15 , разница:  0.98\n",
      "Сеть сказала:  3.1 , а верный ответ:  3.91 , разница:  -0.81\n",
      "Сеть сказала:  3.38 , а верный ответ:  3.63 , разница:  -0.25\n",
      "Сеть сказала:  2.17 , а верный ответ:  2.59 , разница:  -0.42\n",
      "Сеть сказала:  2.79 , а верный ответ:  4.11 , разница:  -1.33\n",
      "Сеть сказала:  3.25 , а верный ответ:  1.92 , разница:  1.33\n",
      "Сеть сказала:  2.9 , а верный ответ:  1.86 , разница:  1.04\n",
      "Сеть сказала:  2.42 , а верный ответ:  2.25 , разница:  0.17\n",
      "Сеть сказала:  3.34 , а верный ответ:  1.97 , разница:  1.37\n",
      "Сеть сказала:  2.02 , а верный ответ:  3.88 , разница:  -1.87\n",
      "Сеть сказала:  3.0 , а верный ответ:  2.4 , разница:  0.6\n",
      "Сеть сказала:  2.4 , а верный ответ:  2.82 , разница:  -0.41\n",
      "Сеть сказала:  3.25 , а верный ответ:  3.71 , разница:  -0.46\n",
      "Сеть сказала:  2.73 , а верный ответ:  3.75 , разница:  -1.02\n",
      "Сеть сказала:  2.75 , а верный ответ:  2.45 , разница:  0.3\n",
      "Сеть сказала:  3.2 , а верный ответ:  1.55 , разница:  1.66\n",
      "Сеть сказала:  2.82 , а верный ответ:  3.62 , разница:  -0.8\n",
      "Сеть сказала:  2.95 , а верный ответ:  4.75 , разница:  -1.8\n",
      "Сеть сказала:  3.37 , а верный ответ:  2.69 , разница:  0.67\n",
      "Сеть сказала:  2.94 , а верный ответ:  3.13 , разница:  -0.18\n",
      "Сеть сказала:  2.48 , а верный ответ:  3.54 , разница:  -1.05\n",
      "Сеть сказала:  3.15 , а верный ответ:  4.64 , разница:  -1.49\n",
      "Сеть сказала:  2.72 , а верный ответ:  2.13 , разница:  0.58\n",
      "Сеть сказала:  2.64 , а верный ответ:  2.44 , разница:  0.2\n",
      "Сеть сказала:  2.22 , а верный ответ:  2.67 , разница:  -0.44\n",
      "Сеть сказала:  2.41 , а верный ответ:  4.31 , разница:  -1.9\n",
      "Сеть сказала:  3.12 , а верный ответ:  3.17 , разница:  -0.05\n",
      "Сеть сказала:  2.85 , а верный ответ:  4.53 , разница:  -1.68\n",
      "Сеть сказала:  2.31 , а верный ответ:  1.62 , разница:  0.69\n",
      "Сеть сказала:  3.02 , а верный ответ:  4.41 , разница:  -1.39\n",
      "Сеть сказала:  3.3 , а верный ответ:  4.36 , разница:  -1.06\n",
      "Сеть сказала:  2.88 , а верный ответ:  3.45 , разница:  -0.57\n",
      "Сеть сказала:  3.14 , а верный ответ:  3.24 , разница:  -0.1\n",
      "Сеть сказала:  3.08 , а верный ответ:  3.15 , разница:  -0.07\n",
      "Сеть сказала:  2.57 , а верный ответ:  1.24 , разница:  1.33\n",
      "Сеть сказала:  2.95 , а верный ответ:  5.11 , разница:  -2.16\n",
      "Сеть сказала:  3.31 , а верный ответ:  4.86 , разница:  -1.56\n",
      "Сеть сказала:  2.94 , а верный ответ:  3.68 , разница:  -0.73\n",
      "Сеть сказала:  3.12 , а верный ответ:  3.08 , разница:  0.04\n",
      "Сеть сказала:  2.61 , а верный ответ:  2.51 , разница:  0.1\n",
      "Сеть сказала:  2.92 , а верный ответ:  3.96 , разница:  -1.03\n",
      "Сеть сказала:  3.35 , а верный ответ:  2.44 , разница:  0.91\n",
      "Сеть сказала:  2.61 , а верный ответ:  2.99 , разница:  -0.39\n",
      "Сеть сказала:  2.97 , а верный ответ:  2.48 , разница:  0.49\n",
      "Сеть сказала:  2.07 , а верный ответ:  4.05 , разница:  -1.98\n",
      "Сеть сказала:  3.05 , а верный ответ:  2.45 , разница:  0.59\n",
      "Сеть сказала:  2.5 , а верный ответ:  3.57 , разница:  -1.07\n",
      "Сеть сказала:  2.58 , а верный ответ:  3.32 , разница:  -0.74\n",
      "Сеть сказала:  2.66 , а верный ответ:  4.79 , разница:  -2.13\n",
      "Сеть сказала:  2.56 , а верный ответ:  2.98 , разница:  -0.41\n",
      "Сеть сказала:  3.41 , а верный ответ:  0.93 , разница:  2.48\n",
      "Сеть сказала:  2.84 , а верный ответ:  3.54 , разница:  -0.7\n",
      "Сеть сказала:  2.43 , а верный ответ:  3.46 , разница:  -1.03\n",
      "Сеть сказала:  2.23 , а верный ответ:  2.16 , разница:  0.07\n",
      "Сеть сказала:  3.51 , а верный ответ:  3.3 , разница:  0.21\n",
      "Сеть сказала:  2.2 , а верный ответ:  2.77 , разница:  -0.57\n",
      "Сеть сказала:  2.86 , а верный ответ:  3.09 , разница:  -0.22\n",
      "Сеть сказала:  2.93 , а верный ответ:  3.65 , разница:  -0.71\n",
      "Сеть сказала:  2.22 , а верный ответ:  3.71 , разница:  -1.48\n",
      "Сеть сказала:  2.68 , а верный ответ:  2.01 , разница:  0.67\n",
      "Сеть сказала:  2.45 , а верный ответ:  3.69 , разница:  -1.24\n",
      "Сеть сказала:  3.3 , а верный ответ:  4.23 , разница:  -0.93\n",
      "Сеть сказала:  2.58 , а верный ответ:  3.13 , разница:  -0.55\n",
      "Сеть сказала:  2.82 , а верный ответ:  3.1 , разница:  -0.27\n",
      "Сеть сказала:  2.96 , а верный ответ:  1.5 , разница:  1.46\n",
      "Сеть сказала:  2.49 , а верный ответ:  3.83 , разница:  -1.35\n",
      "Сеть сказала:  3.12 , а верный ответ:  3.1 , разница:  0.01\n",
      "Сеть сказала:  2.32 , а верный ответ:  3.03 , разница:  -0.71\n",
      "Сеть сказала:  2.67 , а верный ответ:  1.46 , разница:  1.21\n",
      "Сеть сказала:  2.53 , а верный ответ:  3.36 , разница:  -0.83\n",
      "Сеть сказала:  2.97 , а верный ответ:  3.57 , разница:  -0.6\n",
      "Сеть сказала:  2.61 , а верный ответ:  2.07 , разница:  0.54\n",
      "Сеть сказала:  3.08 , а верный ответ:  2.4 , разница:  0.68\n",
      "Сеть сказала:  2.76 , а верный ответ:  3.39 , разница:  -0.64\n",
      "Сеть сказала:  3.18 , а верный ответ:  1.97 , разница:  1.2\n",
      "Сеть сказала:  2.7 , а верный ответ:  3.46 , разница:  -0.76\n",
      "Сеть сказала:  2.81 , а верный ответ:  2.42 , разница:  0.39\n",
      "Сеть сказала:  2.23 , а верный ответ:  3.75 , разница:  -1.52\n",
      "Сеть сказала:  2.69 , а верный ответ:  1.69 , разница:  1.0\n",
      "Сеть сказала:  3.17 , а верный ответ:  2.03 , разница:  1.14\n",
      "Сеть сказала:  3.36 , а верный ответ:  2.39 , разница:  0.97\n",
      "Сеть сказала:  2.82 , а верный ответ:  1.02 , разница:  1.8\n",
      "Сеть сказала:  2.57 , а верный ответ:  4.08 , разница:  -1.51\n",
      "Сеть сказала:  3.05 , а верный ответ:  2.27 , разница:  0.78\n",
      "Сеть сказала:  2.19 , а верный ответ:  4.68 , разница:  -2.49\n",
      "Сеть сказала:  3.13 , а верный ответ:  3.95 , разница:  -0.82\n",
      "Сеть сказала:  3.26 , а верный ответ:  4.38 , разница:  -1.12\n",
      "Сеть сказала:  2.63 , а верный ответ:  2.89 , разница:  -0.25\n",
      "Сеть сказала:  2.76 , а верный ответ:  2.05 , разница:  0.71\n",
      "Сеть сказала:  2.66 , а верный ответ:  2.54 , разница:  0.12\n",
      "Сеть сказала:  2.87 , а верный ответ:  1.83 , разница:  1.04\n",
      "Сеть сказала:  2.48 , а верный ответ:  2.91 , разница:  -0.44\n",
      "Сеть сказала:  3.29 , а верный ответ:  1.87 , разница:  1.42\n",
      "Сеть сказала:  3.28 , а верный ответ:  4.38 , разница:  -1.1\n",
      "Сеть сказала:  2.93 , а верный ответ:  4.71 , разница:  -1.78\n",
      "Сеть сказала:  2.83 , а верный ответ:  3.32 , разница:  -0.49\n",
      "Сеть сказала:  2.64 , а верный ответ:  1.82 , разница:  0.82\n",
      "Сеть сказала:  3.05 , а верный ответ:  4.71 , разница:  -1.66\n",
      "Сеть сказала:  2.61 , а верный ответ:  1.81 , разница:  0.8\n",
      "Сеть сказала:  2.94 , а верный ответ:  3.29 , разница:  -0.35\n",
      "Сеть сказала:  2.5 , а верный ответ:  4.16 , разница:  -1.66\n",
      "Сеть сказала:  2.37 , а верный ответ:  3.82 , разница:  -1.45\n",
      "Сеть сказала:  2.22 , а верный ответ:  2.25 , разница:  -0.03\n",
      "Сеть сказала:  2.92 , а верный ответ:  3.54 , разница:  -0.62\n",
      "Сеть сказала:  2.57 , а верный ответ:  2.89 , разница:  -0.32\n",
      "Сеть сказала:  3.74 , а верный ответ:  2.02 , разница:  1.72\n",
      "Сеть сказала:  2.49 , а верный ответ:  2.83 , разница:  -0.33\n",
      "Сеть сказала:  3.06 , а верный ответ:  3.01 , разница:  0.05\n",
      "Сеть сказала:  2.62 , а верный ответ:  3.86 , разница:  -1.24\n",
      "Сеть сказала:  2.72 , а верный ответ:  2.68 , разница:  0.04\n",
      "Сеть сказала:  2.7 , а верный ответ:  1.42 , разница:  1.28\n",
      "Сеть сказала:  2.16 , а верный ответ:  1.81 , разница:  0.35\n",
      "Сеть сказала:  2.09 , а верный ответ:  3.11 , разница:  -1.02\n",
      "Сеть сказала:  2.98 , а верный ответ:  2.93 , разница:  0.05\n",
      "Сеть сказала:  2.76 , а верный ответ:  2.59 , разница:  0.18\n",
      "Сеть сказала:  2.9 , а верный ответ:  4.64 , разница:  -1.74\n",
      "Сеть сказала:  1.99 , а верный ответ:  4.44 , разница:  -2.45\n",
      "Сеть сказала:  2.67 , а верный ответ:  1.68 , разница:  0.99\n",
      "Сеть сказала:  2.53 , а верный ответ:  3.74 , разница:  -1.21\n",
      "Сеть сказала:  3.0 , а верный ответ:  4.12 , разница:  -1.13\n",
      "Сеть сказала:  2.51 , а верный ответ:  2.11 , разница:  0.4\n",
      "Сеть сказала:  3.15 , а верный ответ:  2.75 , разница:  0.39\n",
      "Сеть сказала:  2.86 , а верный ответ:  3.65 , разница:  -0.79\n",
      "Сеть сказала:  2.54 , а верный ответ:  2.54 , разница:  -0.0\n",
      "Сеть сказала:  2.63 , а верный ответ:  2.68 , разница:  -0.04\n",
      "Сеть сказала:  2.53 , а верный ответ:  3.49 , разница:  -0.96\n",
      "Сеть сказала:  2.68 , а верный ответ:  1.51 , разница:  1.17\n",
      "Сеть сказала:  2.35 , а верный ответ:  1.74 , разница:  0.62\n",
      "Сеть сказала:  2.97 , а верный ответ:  2.87 , разница:  0.09\n",
      "Сеть сказала:  2.63 , а верный ответ:  1.63 , разница:  1.0\n",
      "Сеть сказала:  3.24 , а верный ответ:  1.65 , разница:  1.59\n",
      "Сеть сказала:  2.95 , а верный ответ:  4.11 , разница:  -1.16\n",
      "Сеть сказала:  2.74 , а верный ответ:  3.06 , разница:  -0.31\n",
      "Сеть сказала:  2.95 , а верный ответ:  3.38 , разница:  -0.43\n",
      "Сеть сказала:  2.22 , а верный ответ:  1.51 , разница:  0.71\n",
      "Сеть сказала:  2.42 , а верный ответ:  3.05 , разница:  -0.63\n",
      "Сеть сказала:  3.23 , а верный ответ:  3.48 , разница:  -0.25\n",
      "Сеть сказала:  3.24 , а верный ответ:  4.03 , разница:  -0.8\n",
      "Сеть сказала:  2.84 , а верный ответ:  2.91 , разница:  -0.06\n",
      "Сеть сказала:  2.7 , а верный ответ:  3.32 , разница:  -0.62\n",
      "Сеть сказала:  2.4 , а верный ответ:  2.4 , разница:  -0.0\n",
      "Сеть сказала:  2.77 , а верный ответ:  3.67 , разница:  -0.9\n",
      "Сеть сказала:  2.18 , а верный ответ:  2.89 , разница:  -0.72\n",
      "Сеть сказала:  2.86 , а верный ответ:  2.55 , разница:  0.31\n",
      "Сеть сказала:  2.85 , а верный ответ:  3.46 , разница:  -0.61\n",
      "Сеть сказала:  2.38 , а верный ответ:  2.16 , разница:  0.22\n",
      "Сеть сказала:  2.63 , а верный ответ:  1.85 , разница:  0.79\n",
      "Сеть сказала:  2.74 , а верный ответ:  2.92 , разница:  -0.18\n",
      "Сеть сказала:  3.15 , а верный ответ:  3.56 , разница:  -0.42\n",
      "Сеть сказала:  3.21 , а верный ответ:  2.6 , разница:  0.61\n",
      "Сеть сказала:  2.7 , а верный ответ:  3.6 , разница:  -0.91\n",
      "Сеть сказала:  2.98 , а верный ответ:  3.56 , разница:  -0.59\n",
      "Сеть сказала:  2.73 , а верный ответ:  1.54 , разница:  1.19\n",
      "Сеть сказала:  3.2 , а верный ответ:  4.43 , разница:  -1.23\n",
      "Сеть сказала:  2.76 , а верный ответ:  2.28 , разница:  0.47\n",
      "Сеть сказала:  2.02 , а верный ответ:  2.39 , разница:  -0.36\n",
      "Сеть сказала:  2.48 , а верный ответ:  2.4 , разница:  0.08\n",
      "Сеть сказала:  2.42 , а верный ответ:  1.98 , разница:  0.44\n",
      "Сеть сказала:  2.63 , а верный ответ:  5.05 , разница:  -2.41\n",
      "Сеть сказала:  3.08 , а верный ответ:  2.37 , разница:  0.71\n",
      "Сеть сказала:  2.22 , а верный ответ:  3.0 , разница:  -0.78\n",
      "Сеть сказала:  3.34 , а верный ответ:  3.05 , разница:  0.29\n",
      "Сеть сказала:  2.86 , а верный ответ:  2.71 , разница:  0.15\n",
      "Сеть сказала:  3.67 , а верный ответ:  2.32 , разница:  1.36\n",
      "Сеть сказала:  3.25 , а верный ответ:  1.71 , разница:  1.54\n",
      "Сеть сказала:  2.79 , а верный ответ:  3.65 , разница:  -0.86\n",
      "Сеть сказала:  2.91 , а верный ответ:  1.87 , разница:  1.04\n",
      "Сеть сказала:  2.89 , а верный ответ:  2.58 , разница:  0.31\n",
      "Сеть сказала:  3.07 , а верный ответ:  2.89 , разница:  0.18\n",
      "Сеть сказала:  3.38 , а верный ответ:  2.93 , разница:  0.44\n",
      "Сеть сказала:  2.93 , а верный ответ:  1.2 , разница:  1.73\n",
      "Сеть сказала:  2.65 , а верный ответ:  0.6 , разница:  2.05\n",
      "Сеть сказала:  2.37 , а верный ответ:  4.27 , разница:  -1.9\n",
      "Сеть сказала:  3.16 , а верный ответ:  1.93 , разница:  1.23\n",
      "Сеть сказала:  2.09 , а верный ответ:  4.24 , разница:  -2.15\n",
      "Сеть сказала:  2.29 , а верный ответ:  2.05 , разница:  0.24\n",
      "Сеть сказала:  2.3 , а верный ответ:  2.63 , разница:  -0.33\n",
      "Сеть сказала:  2.26 , а верный ответ:  3.32 , разница:  -1.06\n",
      "Сеть сказала:  2.76 , а верный ответ:  2.34 , разница:  0.42\n",
      "Сеть сказала:  2.73 , а верный ответ:  1.44 , разница:  1.28\n",
      "Сеть сказала:  2.4 , а верный ответ:  1.65 , разница:  0.76\n",
      "Сеть сказала:  2.73 , а верный ответ:  4.15 , разница:  -1.42\n",
      "Сеть сказала:  2.36 , а верный ответ:  2.87 , разница:  -0.51\n",
      "Сеть сказала:  2.43 , а верный ответ:  1.86 , разница:  0.57\n",
      "Сеть сказала:  2.92 , а верный ответ:  2.47 , разница:  0.45\n",
      "Сеть сказала:  3.02 , а верный ответ:  2.49 , разница:  0.54\n",
      "Сеть сказала:  2.26 , а верный ответ:  2.92 , разница:  -0.66\n",
      "Сеть сказала:  2.43 , а верный ответ:  4.54 , разница:  -2.11\n",
      "Сеть сказала:  1.8 , а верный ответ:  1.84 , разница:  -0.04\n",
      "Сеть сказала:  2.82 , а верный ответ:  2.38 , разница:  0.45\n",
      "Сеть сказала:  3.16 , а верный ответ:  2.76 , разница:  0.41\n",
      "Сеть сказала:  3.08 , а верный ответ:  4.53 , разница:  -1.45\n",
      "Сеть сказала:  2.88 , а верный ответ:  2.98 , разница:  -0.11\n",
      "Сеть сказала:  2.53 , а верный ответ:  2.04 , разница:  0.5\n",
      "Сеть сказала:  3.26 , а верный ответ:  2.93 , разница:  0.33\n",
      "Сеть сказала:  2.8 , а верный ответ:  3.16 , разница:  -0.37\n",
      "Сеть сказала:  2.78 , а верный ответ:  3.49 , разница:  -0.71\n",
      "Сеть сказала:  3.05 , а верный ответ:  1.99 , разница:  1.07\n",
      "Сеть сказала:  2.85 , а верный ответ:  2.97 , разница:  -0.12\n",
      "Сеть сказала:  2.44 , а верный ответ:  2.9 , разница:  -0.46\n",
      "Сеть сказала:  2.63 , а верный ответ:  3.3 , разница:  -0.67\n",
      "Сеть сказала:  3.12 , а верный ответ:  3.44 , разница:  -0.32\n",
      "Сеть сказала:  2.81 , а верный ответ:  2.31 , разница:  0.5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Сеть сказала:  3.2 , а верный ответ:  3.25 , разница:  -0.05\n",
      "Сеть сказала:  2.8 , а верный ответ:  2.47 , разница:  0.33\n",
      "Сеть сказала:  3.09 , а верный ответ:  1.69 , разница:  1.4\n",
      "Сеть сказала:  3.02 , а верный ответ:  3.55 , разница:  -0.53\n",
      "Сеть сказала:  2.89 , а верный ответ:  4.02 , разница:  -1.13\n",
      "Сеть сказала:  2.71 , а верный ответ:  3.2 , разница:  -0.49\n",
      "Сеть сказала:  3.04 , а верный ответ:  2.77 , разница:  0.27\n",
      "Сеть сказала:  2.83 , а верный ответ:  3.72 , разница:  -0.89\n",
      "Сеть сказала:  2.81 , а верный ответ:  2.07 , разница:  0.74\n",
      "Сеть сказала:  2.86 , а верный ответ:  3.47 , разница:  -0.61\n",
      "Сеть сказала:  3.17 , а верный ответ:  2.22 , разница:  0.95\n",
      "Сеть сказала:  2.22 , а верный ответ:  2.58 , разница:  -0.36\n",
      "Сеть сказала:  2.29 , а верный ответ:  2.66 , разница:  -0.37\n",
      "Сеть сказала:  2.74 , а верный ответ:  3.41 , разница:  -0.67\n",
      "Сеть сказала:  3.3 , а верный ответ:  2.99 , разница:  0.31\n",
      "Сеть сказала:  2.9 , а верный ответ:  2.28 , разница:  0.61\n",
      "Сеть сказала:  2.79 , а верный ответ:  3.55 , разница:  -0.76\n",
      "Сеть сказала:  2.54 , а верный ответ:  1.71 , разница:  0.83\n",
      "Сеть сказала:  3.1 , а верный ответ:  1.97 , разница:  1.13\n",
      "Сеть сказала:  2.22 , а верный ответ:  5.31 , разница:  -3.09\n",
      "Сеть сказала:  2.23 , а верный ответ:  2.76 , разница:  -0.53\n",
      "Сеть сказала:  2.94 , а верный ответ:  3.97 , разница:  -1.03\n",
      "Сеть сказала:  3.52 , а верный ответ:  0.75 , разница:  2.77\n",
      "Сеть сказала:  2.91 , а верный ответ:  2.58 , разница:  0.33\n",
      "Сеть сказала:  2.31 , а верный ответ:  2.54 , разница:  -0.24\n",
      "Сеть сказала:  2.73 , а верный ответ:  2.65 , разница:  0.08\n",
      "Сеть сказала:  1.86 , а верный ответ:  3.53 , разница:  -1.67\n",
      "Сеть сказала:  3.34 , а верный ответ:  3.46 , разница:  -0.12\n",
      "Сеть сказала:  2.65 , а верный ответ:  4.65 , разница:  -2.01\n",
      "Сеть сказала:  2.84 , а верный ответ:  3.71 , разница:  -0.87\n",
      "Сеть сказала:  2.96 , а верный ответ:  2.52 , разница:  0.44\n",
      "Сеть сказала:  2.71 , а верный ответ:  3.5 , разница:  -0.79\n",
      "Сеть сказала:  2.76 , а верный ответ:  3.28 , разница:  -0.52\n",
      "Сеть сказала:  2.91 , а верный ответ:  3.55 , разница:  -0.64\n",
      "Сеть сказала:  2.37 , а верный ответ:  4.47 , разница:  -2.11\n",
      "Сеть сказала:  2.93 , а верный ответ:  2.7 , разница:  0.23\n",
      "Сеть сказала:  3.51 , а верный ответ:  2.49 , разница:  1.02\n",
      "Сеть сказала:  3.5 , а верный ответ:  2.74 , разница:  0.76\n"
     ]
    }
   ],
   "source": [
    "# Предсказание vs правильный ответ\n",
    "for i in range(len(pred)):\n",
    "  print(\"Сеть сказала: \", round(pred[i],2), \", а верный ответ: \", round(y_test[i],2), \", разница: \", round(pred[i] - y_test[i],2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "id": "ab7967b2",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'mean_absolute_error'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_17572/387398290.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Считаем графики ошибки\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m plt.plot(history.history['mean_absolute_error'], \n\u001b[0m\u001b[0;32m      3\u001b[0m          label='Средняя абсолютная ошибка на обучающем наборе')\n\u001b[0;32m      4\u001b[0m plt.plot(history.history['val_mean_absolute_error'], \n\u001b[0;32m      5\u001b[0m          label='Средняя абсолютная ошибка на проверочном наборе')\n",
      "\u001b[1;31mKeyError\u001b[0m: 'mean_absolute_error'"
     ]
    }
   ],
   "source": [
    "# Считаем графики ошибки\n",
    "plt.plot(history.history['mean_absolute_error'], \n",
    "         label='Средняя абсолютная ошибка на обучающем наборе')\n",
    "plt.plot(history.history['val_mean_absolute_error'], \n",
    "         label='Средняя абсолютная ошибка на проверочном наборе')\n",
    "plt.xlabel('Эпоха обучения')\n",
    "plt.ylabel('Средняя абсолютная ошибка')\n",
    "plt.legend()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "id": "04749776",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEHCAYAAACjh0HiAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAA4lUlEQVR4nO2df5QcZZX3P3cmHTIBzYDMLmEgBFmEFTCJzFHZvPsKrAsqP4ygoru6r7i7rB45CrJxwy5LCLprVhZFRY0c9FVfFQHDjvwUcAFBFHTyixh+rLiIMLAQhQlCJtCZue8fXTWpqakfT3VXdVd33885OZmurq66VV39fJ/nPvfeR1QVwzAMo3vpabUBhmEYRmsxITAMw+hyTAgMwzC6HBMCwzCMLseEwDAMo8sxITAMw+hyZhV9AhHpBUaAUVU9MfTe0cD3gUe8Tdeo6oVJx9t777114cKF+RtqGEZpUeA3v9vOczuqzJ83h7332K3VJrUd69at+62qDkS9V7gQAB8FHgBeHvP+XWGBSGLhwoWMjIzkYphhGOWnOjHJmd9Zz++2PMWnT3o1py89sNUmtSUi8mjce4W6hkRkP+AE4PIiz2MYRmfii8DNW55ipYlAYRQ9R3AJ8HFgMmGfo0Rkk4jcJCKHFWyPYRhtgolA8yhMCETkROBpVV2XsNt64ABVXQR8ARiOOdYZIjIiIiNbt27N31jDMEqFiUBzKXJEsBQ4WUR+DXwXOFZEvhXcQVWfU9Xnvb9vBCoisnf4QKp6maoOqerQwEDkXIdhGB2CiUDzKUwIVPVcVd1PVRcC7wZuU9X3BvcRkX1ERLy/X+fZ87uibDIMo9yYCLSGZkQNTUNEPgigqmuAdwAfEpGdwDjwbrVyqIbRlZgItA5pt3Z3aGhILXzUMDoLE4HiEZF1qjoU9Z5lFhuG0VJMBFqPCYFhGC3DRKAcmBAYhtESTATKgwmBYRhNx0SgXJgQGIbRVEwEyocJgWEYTcNEoJyYEBiG0RRMBMqLCYFhGIVjIlBuTAgMwygUE4HyY0JgGEZhmAi0ByYEhmEUgolA+2BCYBhG7pgItBcmBIZh5IqJQPthQmAYRm6YCLQnJgSGYeSCiUD7YkJgGEbDmAi0NyYEhmE0hIlA+2NCYBhG3ZgIdAYmBIZh1IWJQOdgQmAYRmZMBDoLEwLDMDJhItB5mBAYhuGMiUBnUrgQiEiviGwQkesj3hMR+byIPCwi94nIa4u2xzCM+jAR6FyaMSL4KPBAzHtvAQ72/p0BfLkJ9hiGkRETgc6mUCEQkf2AE4DLY3Z5G/BNrXEP0C8i84u0yTCMbJgIdD5FjwguAT4OTMa8Pwg8Fnj9uLdtGiJyhoiMiMjI1q1bczfSMIxoTAS6g8KEQEROBJ5W1XVJu0Vs0xkbVC9T1SFVHRoYGMjNRsMw4jER6B6KHBEsBU4WkV8D3wWOFZFvhfZ5HNg/8Ho/4IkCbTIMwwETge6iMCFQ1XNVdT9VXQi8G7hNVd8b2u1a4K+86KE3ANtU9cmibDIMIx0Tge5jVrNPKCIfBFDVNcCNwFuBh4HtwOnNtscwjF2YCHQnTRECVb0DuMP7e01guwIfboYNhmEkYyLQvVhmsWEYJgJdjgmBYXQ5JgKGCYFhdDEmAgaYEBhG12IiYPiYEBhGF2IiYAQxITCMLsNEwAhjQmAYXYSJgBFF0xPKjM5ieMMoF938EE+MjbNvfx/Ljz+EZUtm1A00SoCJgBGHCYFRN8MbRjn3ms2MVycAGB0b59xrNgOYGJQMEwEjCXMNGXVz0c0PTYmAz3h1gotufqhFFhlRmAgYaZgQGHXzxNh4pu1G8zERMFww15BRN/v29zEa0ejv29+X+Vg215A/JgKGKzYiMOpm+fGH0Ffpnbatr9LL8uMPyXQcf65hdGwcZddcw/CG0Ryt7S5MBIwsmBAYdbNsySCfOuUIBvv7EGCwv49PnXJE5p68zTXki4mAkRVzDRkNsWzJYMMuHJtryI96RMDccoaNCIyWEzenUM9cQzdTrwiYW84wITBaTl5zDd1Mve4gc8sZYK4howT4bghzT9RHI3MC5pYzwITAKAl5zDV0I41ODOcZAmy0L+YaMtqC4Q2jLF19GweuuIGlq28zHzb5RAeZW86AhBGBiOynqo/HvHeSql5XnFmtwaInyonVNJpJXiGi5pYzAERVo98QeQg4XlV/Hdr+AeCfVPWgxAOLzAHuBHajJjjfU9WVoX2OBr4PPOJtukZVL0w67tDQkI6MjCTtUhfhxgZqPaN64uKNfFm6+rZI9wXUchea1XDl2VFo5FiWJ2DUg4isU9WhqPeS5gjOBm4Vkbeq6i+9A50L/AXwRofzvggcq6rPi0gF+LGI3KSq94T2u0tVT3Q4XqEkRU+YELSWpInLrKODehvgPEcljRzLRMAogtg5AlW9EfggcJOIHC4ilwAnAv87zmUU+ryq6vPey4r3L3r4UQIseqK8pE1cuoY7NhIzn2eYZb3HMhEwiiJxslhV/xN4P3AH8Ergz1T1WdeDi0iviGwEngZuVdV7I3Y7SkQ2ichNInKY67HzxpKaykvUhGYYF8FupDHPs6NQz7FMBIwiiRUCEfm9iDwH3AS8HPgz4OnA9lRUdUJVFwP7Aa8TkcNDu6wHDlDVRcAXgOEYW84QkRERGdm6davLqTNj0RPlJVjTKA4XwW6kMc+zo5D1WCYCjWNRZ8kkuYZepqov9/6fraq7B16/PMtJVHWM2qjizaHtz/nuI88VVRGRvSM+f5mqDqnq0MDAQJZTO5NXAbUy0UkP/7Ilg9y94lguOW1x3YLdSGOeZ0chy7FMBBrHymikU1dCmYjsEfD/x+0zAFRVdUxE+oA3Af8W2mcf4ClVVRF5HTVh+l09NuVBlqSmsoeadmrIZSPhjsuPPyQyMsylMc8zzNL1WCYC+WCBIOnEho8mfkjkN6q6IGWf1wDfAHqpNfBXqeqFIvJBAFVdIyJnAh8CdgLjwMdU9SdJxy0qfDQL7RBqGhdyOdjfx90rjm2BReWg7ALuYyKQHweuuCEySkWAR1af0GxzWkZd4aMi8rG4t4A90k6qqvcBSyK2rwn8fSlwadqxykY79DAsCiqarKUsWiEcVko6X6yMRjpJrqF/BS6i1lsP09WlKdqhkW33hz/csB1z6AC3P7i1roauDLkDrjRSSrrT3IB50YhLsFtIEoL1wLCqrgu/ISJ/U5xJ5acdGtkiH/6ie59RDdu37vnN1PtZGrpGGsm0kV/e96GIUtImBFZGw4UkITid+InbSD9Tt9AOPYyiHv5m9D6jGrYwrg1dI41k0sgv7/sQJwIuYtMOI9RWY9Vtk4kVAlWNzbJR1aeKMac9aJceRhEPfzN6n64NmMt+jeYOxI388rwPSSLgIjbtMEItEzafMpPE8FEv0/dpVd0qIq+gFv65B3Chqt7fDAPLSjf0MKJ+MM3ofcY1bFH71Xss19yB8MhPINE2l/sQvK/z581h7z12477RbTPcQa5iU9YRalqD24oG2eZToknLI1gDnOL9/S/A/wCbga8BbyjQLqPFxP1g5vVVGBuvztg/z95nVMMWxrWhyyt3YHRsHCG9WFbafQjf1ye27eCJbTt4+5LBGXMCcaIyOjbOgStumNF4lqmXm9TgAlxw7ZZpz9Ho2DhnX7mRkUef4ZPLjijMLptPiSYpfHQl8EfAh0REgLdTE4BDgf1E5HzgDlW9symWthGdMPSM+8HMqfTQV+kttPcZ1bDVGzW0bMkgI48+wxX3PsaEKr0inHpkfaO5NBFwuQ9x8x8/e+SZGduSRkbBDFko3wg17vlZdd0WdlQnI++BAt+65zcMHbBXYddi8ynRJM0RrBKRZcB3gH2oVR09F0BE3pS2bkC3UtahZ1Cc5vVVEIGx7dXME5DPbq/S31dhTqUn8fONklfDNrxhlLXrRpnwEicnVFm7btSpsYlKHIxCwPk+ZGmIXEZGSb3ZVnZIkp6fNFZdt6UwO20+JZo019CF1BaXqQLvhql5g98WbFfbUsahZ7hBCw/Js0xA+p/vq/Ty2dMWl6oXGkUj34dL9FLWTO358+bwxLYdM7ZHNUS+fauu25LYgEY1ukV0SLIIi+s8TxQuYlEvZZ1PaTVpZaj/Q1X3VdUDVPWn3rYtqvr25pjXfpRx6JnWoEWVYk4r/VxvLf6iOW94MwedeyMLV9zAQefeGNsY+d9HUmG+tO8sawNSnZhk7z12y3ycHdXJxONGiUie6ydA9sJtcYX1+vsqdZ0/LzqxuGQe1FV0zoinlUPPuB5bPWGW4YlSl8+0mvOGN09LPJtIqKO1b39faq85qVebdYnM6sQkp37pJ9w3ug2AXhEmVFOPkybicSKSd4ck68gqbgIbcHK3LVxxA/19FS44+bDSuh07CROCnGnV0DOpUXMZpse5JpYtGYwtYKfUituVZTL8insfc9rP/z7SGre47zKuBxknxGERgJpIVXqFF17cydlXbuSimx/KNFcDyWKUd4ekHmFJanCTOhg+Y+NVll+9aepYRnGYEORMq0L5khq1tEnHNKFK+vzo2DjLr97Equu2OE0eFzmBmTQCGOzvmxaB5DLSyfJdxgnxxKRyy/3/M00EfKoTOjVfk3WuJm1uIu8OSZ7CEhQI/3mI+y6qk9r1oZ3NwISgAFox9EzqsYUbNJeooSB+COa37/lNZAhldVKnJviSJiWLjqjy3S1R2/1Gc3jDKMu/t4nqRLLbyMf1u4wT4n8a3pzq4w/u75osdsyhAyxdfVusQOXdISlqpOvf37hS0ZA86uiEUO0ykFkIROQB788vemWkjRKQ1mNrVJxuf3Brahy9T1xhtp6IhjrPiKr3vH7/aXMEwe1pPU+fehq34Q2jscfdUZ1k5Umv5vP/+UunaJikuZrgiGbtutFUQW3kO49qYD91yhGFNbpJ7su4UUdZQ7XbkcxCoKp/7C0n+foC7DHqpOi5iayhgFGF2eJcN3lNOvsZqcHksfe8fn+GDtjLaYKynmQz/xqT+NwPf8lzO9xCIv1GL6mnu3T1bYWGKMc1sJ865YjCFjVafvwhkSO1So+w/PhDIu9HGUO125W6XEOq+lvghpxtMRqg6LmJOLdLHHGF2eL2zYtPLjtiRomCqIYziizJZj4u1xhVkiMKX7jTerpFhSgnjZqKbmCjcib8qCEg8n7E3feyRbO1A6lCICI7ge3UEijnADsAzbqAvVE8Lq6Aen2qWUTAb9DOvnKj875xNvbPraAK28brz2LO0jBkbfAabXSCk9j+taX1+IsIUXbJoi66gY17fhevuiXyfsR1Tro9S7geXEYEm1V1CYCIbPD/NtqPRnyqgykhqL0iTKpOa9DiepdR+8bZGPSr1+sDzprlOjo2zkHn3hgZ5x8W0rgifC7ERf6k9fiLcAO6jGxa0cAObxiNvb8TqoXXveoWXJac3A1ARGYDrxSRC7widEab0Ui2aVqm8YQqj6w+gbtXHDvVaMZll178rkU8svqEKT9vMKvXJQv6rCs3zsgCbsT2uOuB6Rm0Udm1L7wUtZJrOkkNVlyDG5z4zzs7Nu8s6rxIejb96w7eh1OPHJzxTBnpuIwI7hSRTUAFuAR4DrgReEuBdhkF0Ihv2W9kzrlqU6ybyA8BDPeio1xRcaMTF19+cP+gbWm2B8NnX3hpZ2IIaZCgWIbtq04ovQIuh9pzbsUpZNelx593iHL/3EpsVFPWLOo8SXo2fZuCozWLIqqPVCFQ1Q+KyOHAhKo+ACAiPy3cMiN3GvUt+z+ms6/cGBlK6m9zKY8cNzrJMik9Xp3gnKvcMk+DdixdfVtmd05SgzSh8PYlg/zskWdiXVB7zq2w4fzjEs8RrhAbV+G1iNj5uFve31cpLFIoSNw1xT2ze86tzLhmiyKqHxfXEKr6C18EvNepQiAic0TkZyKySUS2iMiqiH1ERD4vIg+LyH0i8tps5htZiHPVZBnyL1sy6JRPkOZyimtYfb+vKxOqM4qfJRWSSzp3Evv298UK5ry+Cp89bTF3rziWS05bHHmPV550WOLxw26nsfEqO6qTU8cN93pdi7+5si1GGOO2B+1OutcuJF1T3DMbdT/LWPCxXUgVAhH5vYg85/37vf/a4dgvAseq6iJgMfBmEQmvavYW4GDv3xnAl7OZb2QhL9/yoOMIIukHGNeo+jbtOde9SmVQdFwayrhzJ018vfDiTo45dGBGo1TpEVadvKtRqvceu87fJC340ghp8xJR5CVKaT151/tZzzUYNVxGBJ8DfgG8R1Vf5v1LDR3VGs97Lyvev3Bn8m3AN7197wH6RWR+BvuNjCxbMsjdK46dMbGbBdfJ16QfYNLoZNmSQebOzpbiMuolsLk0qHHn/ss3LIgtkzw2XmXtulHevmRf5lRqP5t5fRUueueiGfewnnvs2ptNWvClkVFBPaPFvEpdp1276/3MY8TbrbjMEZwnIgPAP4vIx4DzVfVul4OLSC+wjtqSl19U1XtDuwwCwZKRj3vbngwd5wxqIwYWLFjgcuq2pB7fbzAJyLW0caNEJf+ESfsBpiXA1TOcT5psDq/zG1UuAWDtuvjGdLw6wTUbRtlRnWReX4XnxqvTGr1GvgfX+ZukUFh/Za9GFo3P8vzlVZ48r7yI4DX430NQmPLKuu7E2kYuCWW+3/7rwIHAl0TkMVU9Me2zqjoBLBaRfuA/RORwVf1F8PBRH4s4zmXAZQBDQ0PumU0lJvxAudaPCR8jqoRDM6Il/MnXrELk+kOqZ4WrtMlm332x/OpNXPTORTMmQV0ykHdUJ6n0yJTvfHRsnOXf2wRaK74Hbt9D+D4sfEX09R5z6MC018uPP4SzYhL1nt1eZcmFtyTmXqRF1oQFI66w3fCGUYTodZyzNuB550Vs90J68/49dHJUkmhKhIaI3B61XVWPyXQikZXAC6r674FtXwHuUNUrvNcPAUer6pMxh2FoaEhHRkaynLp0RGVxxv2oksoNx60T4PLZsD1xIZ559n6irjuuvr/resFRhJOMoujvq7Bx5fQonqQKmD5x31MS4e+h0e9/4Yrs1V3848Q9M754+9/3nEoP46GqqcHvKu44AnUtYZrHs5b2zGRdVjRM0r1rRmRVo4jIOlUdinrPxTWUqcEPnHQAqKrqmIj0AW8C/i2027XAmSLyXWpF7LYliUCnEOVbracEb9oQ3GWIHtfLuXrkN/zkV8/EhoTWQ5xP+ZyrNnH2lRunNQBRroqtv9/BSw4B+3MqPew2q4dt49XY+xoVPpo2Cqn0yFSvPwvh76GR77/eeQD/uuKeiXAeR1gEatt2TeDGHUep7/moNy8irbptkEajhzo5KsnFNXR+1HZVvTDlo/OBb3jzBD3AVap6vYh80Pv8GmqJaW8FHqZWz+j0DLa3LVkenKRhdlrD5TJEv+DaLZGN892/embGvo3GZCeFjEK0myJ4riUX3sJLDqWcn91epdIrfPa0xbFulCiSFuCZ11fhpEXzpyqbZiH8PWT5/ntEOHDFDVM1l+otZ9HrFQNIemZcRl+jY+MsXX1bbGkN14iyPHCtbuvTaPRQK5ehLRqXqKEXvH9/G/j7hbQPqep9qrpEVV+jqof7wqGqazwR8COLPqyqB6nqEara3j4fR1zDF11WDouL3nHxsSbVcYmjkd6Pyw8mKepkzEEEfKoTyqrrtsSGoUZtD4YqAlPRQStPejWrTj6MtetGIxubnoS406jvIUv46oQqSk3c6hUB/zhQX7mNMH5pjUrowpsdoeNa3Rbysa2To5JShUBVL1bVi4Hf+n97r406SQpfzBJ/Hm64/F5fltj1rDTS+3FthOLEJuu5n91eZeVJh1HpndnEnvCa6CjlZUsGuWP50Rx/2B9OLSpz+tIDI0dOACLQG6MEwaiVoEvH5fvvraOcV7hhDuI/I+G4/HrOAzWh3WPOrFzrHcURl7Tm2inp76vkYlsRNZ7KQupk8dSOIutVteWZv50wWQzlCENzmRwNUu9EYBAXn27c5Fs9E8i/Xn0C5w1vnrHMZtwkdXVikjO/s56btzw1FSJaT4XR8ORv+HzDG0Yja+/772f9bvwRTtIqaOFz1HOeIAI8svqE2PeLmgD272U91W27mYYmi0XkOmrP9CtF5Fp/u6qenJ+JnUGWBz/vomH12JI1RPMv37Agl15VXJEwnxde3Ml5w5u5/cGtibHuaZODfnJY1DKbUfMdQREIhojW45JxOV9wLeOx8eq0+ZGs382r578scl4nyNh4leVXT6/NFHceoVaIbmx7NfY+u2QdNxpqmZS0Fhd22im99GbiMkfw78DF1LKALw78MwIUVQOmSFuiXBRJjoLbH9yaeD1Z6874Q+2wv35svMq37vnNNPvPunIji1fdwsijuxq7JBGo9AgnLpqfGGIbdC2ERwKu0UFZHCvB86Vl5Wb1O/8kRQR8qpPqlGX92dMWs+H843hk9Qlc/K5Fpcw67mRXTbNxCR/9UTMMaXfKVPkwiy27zeqZ2nfPuRVOeM38aYltQdISpOrpAfoL2Lgs7O4LRBq9Ipz2uv1jr8PH79EGRWDlSa/mwuvuTz2Hj+KeWzAvUL7CpazCx67aiGu0ahb3TvDcLhnFaeXEo7bnFWqZFqlT9Mi6W3BxDb0B+ALwx8BsoJdaYpgtVRmgTDHGLrZEuWV2VCcZOmAvhg7YK/PatY0IYZ73SKiNFNLCPP0ebVgETl96IJff9YizWyZt5bZptgWGDy6hiH/x+gVOwpeVsEvHpTGN2idJ/PMKtSxiNTZjJi6uoUuB9wC/BPqAv/G2GQHKVPnQxZa0hvvuFcfGuj2iGu64xtCv8RPnKhreMEpPTgveBXvmSSLguxBOeM38GSIA0e6SqIAcv0FyjZ33w1+HN4xOlUEIH++YQwem3Gu3P7iVpQftRZ7rAVZ6JLdGNM1/n0eopbl/moNTiUdVfVhEer3aQf9XRH5SsF1tRxl6LsG6P1FRK0FbXEYNrr26pLozwLR5CtjlavB7lFkTtML4DbFLz9yPSIoaCfj49l1w7ZapieJ5fTW3WXAC+5hDB2LvdxT79vfFTpD391U4cdH8GfWmnhgbp6/Sw/aITN+szK308K+nvCa3RjTNfw/ZitjFYe6f4nERgu3eesUbReTT1CqD7l6sWe1Hng9+GlF+WZhefTPou44qAufSyLuK20U3P5RpsZrgvaqnllAQ356zHTOIF76iL1EEgry4c1fj++z2WhlqvzcabtDTrt+3M+6ad99tFrc/uDWy9EQeIgDw4k7l7Cs3TvXYG302456hHhGGN4xaA95GuBSdOwB4itr8wNnAPOBLqvpw8ebNpFPyCOolLiZ+t1k9sSn/rjH5UaF3LmGoWWPRf+3FnjcSw+5ziZfXkFaAL8hrBudx3+i2RBFIKzDmcj5fiINVWbNWVM1CloJ4eYRZJuV1WBhn+Wi06NyjIjJbVZ8TkYuBV6jqo7lbaaQyvGF0hghAracd17OOKlrmN+z9cytTxdniGnmXXl2WmPdgJms9paaDDPb3TdmWVCcoTJoIQLrrzGWC2x+VBWspFUkWUc0jos3/7DlXbZrh3rO1gtsLl6UqPwFs9cpI3w7cKSL/XLhlxgxcXTBBgq6e84Y3c/aVG6fi85/dXuXFnTPXxXXFzxvwfeQuBBsMl5ITcccV7/O+DWdfuZHdZvWw59yKU+mEJBGA9Al31yCAMi+e4a/q1gjLlgwyGeNVKEtVzjzWVe50XKKGTgUOAJYDxwFHAO8t0igjmqw/rKA/P2k0UU/NoWDSGuzq/UKtpx635GMwwiYqIuS9oXpLSRPQAMuv3jRtwffnd+zks6ct5uJ3LYoVEZcon7SolzyKtxXJnnMrTvWE8kh6LFPEXJgyJXqWGafJYm9NgdtU9VkAESmH1DtShro+eZDVlRL00SaNJsL5BS4rjsXV1Pd96HFzEOGJ5jTXU5wvvr+vwgXXbpmRAVydVC64dgsbVx7HyKPPzIjDdwmfDK59HHcPwsEB/XMrPL9j5zR74nz2ab78/r4Ku+82K/W7TlqNbWx7lQ3nHzd1PXFuszxcOK2OmEtberPRRM8ytB9F2+AyIvgJ7KotJCLzgKdzs6BgOqlHkKUX6vvPg+6bOPyeW7iXH14nIHjPXDJj84j/Xn78IZFVNV94aWdsDSB/+5L995w5KkjxYUXdA79Ri5o/8RdV33D+cVz0zkXTrvcv37Agtspo3Iipr9LLBScfxt0rjuWS0xYnlhm/+F2LYkc3+0aMvOJIy/VIo5Wx/mm/70YTPcvQfjTDBpfJ4o+EXm+j5iJqC8pU+qFRkibngvgNl0u1Tt/XDtGL1PiE71lS6GBwkfhGl/BbtmRwWpVOn2rKSmXViUn+aXjzjJ53dUITv/u0GjlppRjCx/WztMOhvmvXzfwRh6uDBnu1SSM015FXXLY4xOd6uNKqUNG033ejGc5laD+aYYNTQpmInAAcBszxtzmsUFYKylT6IQ/ifvxROQNpi7ELuyqKuixSE7xncVE6eS8YDtkWpAHo75vFmd9ZP626Z5B6lv8ML+WYpZZS+P2472X33WZljtrKkr/iElmVZwPTDJdK2u+7UbdVGdqPZtjgUmtoDTAXOAa4HHgH8LPcLCiYdlheLusPxvXHn/SghHuVLhPGYXdD0IaoUsV5NSpZ5kZm9cCCvXafqiK6LWZt4qzn8heZCRJ1fS7fZZLY1INrbzz8ndWzTrZP2nXmVYY6DZeidFB/omcZ2o9m2OAyR/AnqvpXwLOqugo4Ctg/NwsKpuzLy9Xr/wv6p+NCP+MeFH9CN/iZtB9/nLvBt6HIEMIscyOvnr8rWWzVyYdl/u6POXQgcnucKy6qkF/ad5m0VGXRvufgd+YyvxCFy3XmVYY6DZfft8tvpZHjF00zbHARAv9J3y4i+wJVIDkIu0SUvWhVkT+YuAcoWNjMnyBM+vGn3bOkwnF59FrC32FSOGQwWaye7/72B7dmss21kF+Q5ccfEjlnrdS3fGgacXH09TYwLtfZLJdK0b/vMrQfzbDBZY7gehHpBy4C1lN7Xi/PzYImUOaaJ0X+YKKGxcccOjCjsNm512zm1CMHZ9TvdykTEFXyIvj5vHotwe8waRK80iPsOXd25OdcyHLfgxPtSZ8Nb1+2ZJCzYmojjY6Ns3T1bZGulnrcGy4umqzHzbNgYR4U/fsuQ/tRtA0uUUOf8P5cKyLXA3O8yKFERGR/4JvAPsAkcJmqfi60z9HA94FHvE3XtMskdF4U/YMJP0BRE5Xj1Qluf3Dr1Dqwro1CXJJa8Lh+LzHPhzgpespfgave82WZj1CmX1eW7zKp7lC4sW7E354WcVJPAxN3nfP6KixdfdtUXkWlR6blVZTJJWtMx2Wy+E2q+kMAVX1RRF4uIt9V1XenfHQncI6qrheRlwHrRORWVQ0v/3SXqp5Yn/ntTzOScYK9yaQJwqyNgkvJi6ImCZN61Vl69cMbRqeVm959du+MBiwuASzsY8/yXaZF8AQb67jG/JyrNnH2lRsTRTtpmc56RxlRtld6ZFpux7Pbq1R6hX5vwr6dEzm7ARfX0AUiMqCqV4jI6dRKTaT22lX1SWolq1HV34vIA8Ag4L4OYBfQaFRDGi65BFDfCMS1wa03eiipoapOTDKn0hMZIup6LcMbRll+9aZpjf4LL03Q21NrwMbGq1Ox+2nrO0C27zKcIxBFWoG7tFDdpHUi+udW6h5lRF3n9pd2RuZ67L7bLDaubJu0o67FRQjeDFwlIsuBTcD/UlW3lbI9RGQhsAS4N+Lto0RkE/AE8PequiXi82cAZwAsWLAgy6nbgiL9fy41/+sdgWRxo2Sd80hyh/gri+2oTjbkfrjo5ociF6mfmFREasdyXd/BJ8t36e8bl/kdLHCXdp/DYju8YZRzrtoUX+JCaShJKXydB664IXK/ds3X6TZcooZmAx8ARoFnABWRvVxPICJ7AGuBs1T1udDb64EDVHURtXWRh6OOoaqXqeqQqg4NDESH9xnRJP0QG4lAiFtuMY6sI444d8inf/DgtEVlwmUdslxL0r15dns1sZZSnsKdV4E7/3rSVn5TiMyvCB4jK2UuPGek4zIiWMeuDtHhwCne61emfVBEKtRE4Nuqek34/aAwqOqNIvIlEdlbVX/raL+RQlxvMm7BGp8kt0yW5RYhupee5p+OjUzZtoMntu2Ytp5AMyaGo+zKK3M2yaUUVQAv6Xr84ySNApOW9qy34S56rqsMhd86GZeoobpyBkREgK8CD6jqZ2L22Qd4SlVVRF5HbYTyu3rOZ0Sz/PhDZvjB0ypwpkWpJC23+MllR0TW18madZrUSKctKuNK1L1Jo39uZdoaDP4nG50Uj3Iphe9T1FyFTzCUNalXH2yc82y4XedH6mnQm5Wl3M24RA19mFqPfsx7vSfwHlX9UspHlwLvAzaLyEZv2z8CCwBUdQ21chUfEpGd1BLX3q1pa2ca2QlnL6VU4EwLOUwKe4R0P7lLEa3lxx/C8u9tmlFc7u1LBnMRAd9OgHOvuY9xb9K5RyBJF57fsWtSNG5th7wap7hS32ExCNaMguQyGWHXWZ697LTvvd4GvQyF3zodF9fQ36rqF/0XqvqsiPwtkCgEqvpjUpocVb0UuNTFUKM+Lrr5oRmNaVoFzrSEoTgXRVzGb7gXmBYlM0XoFD0Cb3xVEXNEu+ye1IR1BITU0UOek6Nxx/LnKuIa8Dg3TVAEmulqCa5xEcalQS9D4bdOx0UIekRE/J66iPRSm0A22oCkH1FcY5CWGBXnp47aHtULjGtow+Uawo3upJJ7LzCu1x0mGEGURJ6To/XO76S5aZrpanEJX456RoPPZlRBQ7CJ6DxxiRq6mVr46J+JyLHAFcAPijXLyIu4H4sfRx5VOCwtiiWuWFnU9iT3RtzxITkRKk9cjrfn3MpUrZck8k4EbKTYWFKhtWYVhIs7V5jwMxouahclApalnC8uQvAPwG3Ah4APA/8JfLxIo4z8iGtM0uLIk4pcZWmg0twbUcf3k8WiyLsX6HK8ubNr6wREXXdwnea8C4EVVWysma6WeqraxolHr0gpC0d2Ai5RQ5PAl71/AIjIa738gPst1LO8JK29e3ZKeYakib8sGbRZ3RvViclMyWJx7i1XH7jLYi3BewJMK0nRP7fCypMOK6xRKiLZsJkF4ZLmhOIS8+LEY1KVR1afkLuNhlvU0OcjNp8GrKKWZGZCUEKiQg+Da+/GTd65NgbhBsovdRxueLPEl/si4CeL7Tl3dl1hqCOPPhNZYdW3O3wdkFzqIXxPXty5q6zFs9urbRfK2MzF5l0mrsOUYTGYbsNlsvhtwPmhbSc7hI8aLSQt5C7PxiCPUsdhEXBJFou7xivufSxytbQLrt2SWBYiamIzfE86IZSx6PpWjZ6rmUJl1JC0sH0RWa+qrw1t26CqSwq1LIahoSEdGRlpxanbigNX3BCbeOQPr/MKIYyrlZMW3eITJwJpxF1jEpectjjxGs8b3jwlJALMnd3L9pcmpu7P2VduTL2vWbCM2WjsvuSPiKxT1aGo91xGBAeLyA+p1Rl6HLie1JQko9W4DK/z8j83MvlYrwhAcuJUXIhrUs99eMMoa9eNTn1WqVUjhV2jnHleVdIoW7JiGbPxFFmI0ZiJixAcDfQCe1BbovLvgSO8hWd+q6qW1VFCmjm8ThOduN5dIyIA8RO9u80StlejhWA0IX8iLdRxvDpBj8xMOKv3vhbtZgpe57y+CiIwtt3WBjBm4hI1tC606asi8mlqk8VfBn5ehGGGO0nD6GYMr5NEJ67X+7NHfsc1G0bZUZ1kXl9l2vKSrvjXsuq6LdNq4W+PWKNgmr2B0hXBXrjLCMYfIfgIcOqR9fVeiwzjDN/34CjGRh7NpR3cXC4jAkTkAOBgVf2hiPQBn1DV3xdrmuFCmnuhGQ9ckujELY35nZ89NvV623j9kTd+Tz68KEoS4ZIb49UJVl23pa5qpEr2Be99ioyOcRndtNMEdxplbWzbxf2XmlDm1RX6HvAVb9N+xKwbYDSfZmaJJhGXyZp1FbN6yKMH/ez2KsccOuBU9z+v8zeSOZyHTZ1SqyeciRzMkm81Zfl9puGSWfxhapVEnwNQ1V8Cf1CkUYY7ebsX/HyAA1fcwNLVtzX8Y8rSu817UZSejCENtz+4lVOPHIyMhNhzboX+vkqm86dRVOawq02dEpdf5sa2XQrmuQjBi6r6kv9CRGYRXZfLaAF5rgxVRM/KdXUtaGxRlEpvRPOtzNheSVCHJ8bGuf3BrZEP99zZszhx0fzUGklZSaoJ1Ahp972T4vLL3Ni2y8ptLkLwIxH5R6BPRP4cuBq4rlizDFfydC8U0bNatmSQTy47PHW/RhdF2X32zOmuSWD32bOm9bgveueixJ59XOMxOjbO2nWjM9YBqHeiuGjCo43+vgp7zq10ZK2eMje2Rbr/8sRlsngF8NfAZuDvgBuBy4s0ynAnz+igInpW1YlJbrn/fwBm1A5yWQzelbg1eLeNV9m48rgZ2+OinOJKTfSKRFZRrXeiuBl0Syx+mTORmxm91whORedE5BvAvdSe/YdsFbFykdcPPu8olqy1gxohi+1pP86oRiUuAqcM7oey0qxInrI3tu0gyC5F504A1gC/otaJO1BE/k5VbyraOKO55Nmzqqd2UCNktT3uxxnXqLgU6StrCGMraHbYZDs0tmXGxTV0MXCMqj4MICIHATcAJgQdRl49q0Yzhushz15hXKOSJDTtEi/eKK5i1wnF+boJFyF42hcBj/8Gni7IHqPFNNqzaoUI+BTZK0wTmm5o+LKIXZkjeYyZuAjBFhG5EbiK2hzBO4Gfi8gpAKp6TYH2GW1EniJQRjdLktB0Q8OXRexsTYH2wiV8dA7wFPBGagXotgJ7AScBJxZmmdFW5C0CZc0UjaPMIYwuuCQSZhG7dgmbNGq4RA2dXs+Bveqk3wT2oRbSfZmqfi60jwCfA94KbAfer6rr6zmf0Trydge1o5ulzCGMabi6fPKMzDLKRawQxCxROYWqfiTl2DuBc1R1vYi8DFgnIreq6v2Bfd4CHOz9ez21aqavd7LcKAVFzAm0o5ulnRs+V+HNKzIriTK6BLuBpBFB1BKVzqjqk8CT3t+/F5EHgEEgKARvA77p5SXcIyL9IjLf+6xRcoqaGG5X/3K7hjC6Cm/RYtctkVdlJEkInlHVb+RxEhFZCCyhlpQWZBB4LPD6cW/bNCEQkTOAMwAWLFiQh0lGgxQZHdTObpZ2JKvLp6hGuR1dgp1C0mRxLtnDIrIHsBY4S1WfC7/tcl5VvUxVh1R1aGBgIA+zjAYoOkS0yKqcxkzKMrHbji7BTsFpYZp6EZEKNRH4dkyY6ePA/oHX+wFPFGmT0RjNyhNoVzdLO1KW+Y12dQl2AklCsEhEwj148GqFqerLkw7sRQR9FXhAVT8Ts9u1wJki8l1qk8TbbH6gvLQyWcwoljIIr7kEW0esEKhq9qWaprMUeB+wWUQ2etv+EVjgHX8NtUqmbwUephY+WleoqlE8JgJG0ZRlZNKNSLsVEh0aGtKRkZFWm9FVmAgYRvsjIutUdSjqvULnCIz2x0SgXFicvVEEJgRGLN0uAmVrdC3O3igKl1pDRhdiIlC+ekdlXqTdaG9MCIwZrF33OEdccDM3b3mKeX0V9pw7u9UmNZ0yNroWZ28UhQmBMY216x5n+fc2saM6CdTW/G11T7gVlLHRbfcKp0Z5MSEwpqhOTPJPw5uZDAWStbon3ArK2OiWJQPY6DxMCAxg15yAPxII023uhzI2ulZ6wygKixoypk0Mz+ursG28OmOfbnM/lDW5qQwZwEbnYULQ5YSjg/acO9vS/D2s0TW6BROCLiYpRLRsPWHDMIrDhKBLSRIB6wkbRndhk8VdSLcnixmGMR0Tgi7DRMAwjDAmBF2EiYBhGFGYEHQJJgKGYcRhQtAFmAgYhpGECUGHYyJgGEYaJgQdjImAYRgumBB0KCYChmG4YkLQgZgIGIaRBROCDsNEwDCMrBQmBCLyNRF5WkR+EfP+0SKyTUQ2ev/OL8qWbsFEwDCMeiiy1tDXgUuBbybsc5eqnligDV2DiYBhGPVS2IhAVe8Eninq+MYuTAQMw2iEVs8RHCUim0TkJhE5LG4nETlDREZEZGTr1q3NtK/0mAgYhtEorRSC9cABqroI+AIwHLejql6mqkOqOjQwMNAs+0qPiYBhGHnQMiFQ1edU9Xnv7xuBiojs3Sp72g0TAcMw8qJlQiAi+4iIeH+/zrPld62yp50wETAMI08KixoSkSuAo4G9ReRxYCVQAVDVNcA7gA+JyE5gHHi3qmpR9nQKJgKGYeRNYUKgqu9Jef9SauGlhiMmAoZhFEGro4YMR0wEDMMoChOCNsBEwDCMIjEhKDkmAoZhFI0JQYkxETAMoxmYEJQUEwHDMJqFCUEJMREwDKOZmBCUDBMBwzCajQlBiTARMAyjFZgQlAQTAcMwWoUJQQkwETAMo5WYELQYEwHDMFqNCUELMREwDKMMmBC0CBMBwzDKgglBCzARMAyjTJgQNBkTAcMwyoYJQRMxETAMo4yYEDQJEwHDMMqKCUETMBEwDKPMmBAUjImAYRhlx4SgQEwEDMNoB0wICsJEwDCMdqEwIRCRr4nI0yLyi5j3RUQ+LyIPi8h9IvLaomxpNiYChmG0E0WOCL4OvDnh/bcAB3v/zgC+XKAtTcNEwDCMdqMwIVDVO4FnEnZ5G/BNrXEP0C8i84uypxmYCBiG0Y60co5gEHgs8Ppxb1tbYiJgGEa70kohkIhtGrmjyBkiMiIiI1u3bi3YrOyYCBiG0c6IamTbm8/BRRYC16vq4RHvfQW4Q1Wv8F4/BBytqk+mHHMr8GgB5ubF3sBvW21Ek7Fr7g7smtubA1R1IOqNWc22JMC1wJki8l3g9cC2NBEAiLuQsiAiI6o61Go7moldc3dg19y5FCYEInIFcDSwt4g8DqwEKgCquga4EXgr8DCwHTi9KFsMwzCMeAoTAlV9T8r7Cny4qPMbhmEYblhmcf5c1moDWoBdc3dg19yhFDpZbBiGYZQfGxEYhmF0OSYEOZFWW6nTEJH9ReR2EXlARLaIyEdbbVPRiMgcEfmZiGzyrnlVq21qFiLSKyIbROT6VtvSDETk1yKyWUQ2ishIq+0pGnMN5YSI/G/geWplM2bkTXQaXjmQ+aq6XkReBqwDlqnq/S02rTBERIDdVfV5EakAPwY+6pVI6WhE5GPAEPByVT2x1fYUjYj8GhhS1U7JIUjERgQ54VBbqaNQ1SdVdb339++BB2jjEiEueHWxnvdeVrx/Hd+TEpH9gBOAy1tti1EMJgRGw3gZ5EuAe1tsSuF4LpKNwNPArara8dcMXAJ8HJhssR3NRIFbRGSdiJzRamOKxoTAaAgR2QNYC5ylqs+12p6iUdUJVV0M7Ae8TkQ62g0oIicCT6vqulbb0mSWquprqZXL/7Dn+u1YTAiMuvH85GuBb6vqNa22p5mo6hhwB8lrbnQCS4GTPZ/5d4FjReRbrTWpeFT1Ce//p4H/AF7XWouKxYTAqAtv4vSrwAOq+plW29MMRGRARPq9v/uANwEPttSoglHVc1V1P1VdCLwbuE1V39tiswpFRHb3AiAQkd2B44COjgY0IcgJr7bST4FDRORxEfnrVttUMEuB91HrIW70/r211UYVzHzgdhG5D/g5tTmCrgin7DL+EPixiGwCfgbcoKo/aLFNhWLho4ZhGF2OjQgMwzC6HBMCwzCMLseEwDAMo8sxITAMw+hyTAgMwzC6HBMCIzMiMhEIGd0oIr8RkUtbbZdRHCJyQcS2fxGRx0Tk+fC+IvL33t9zRORWEVnZJFONOjAhMOphXFUX+/+A81ttkFEMIrKHiFxFrczCfSLyb4G3ryMh41ZEZlPLPF+nql1TsrsdMSEwckVEvi4ia0TkLhH5L69WDSKy0Nu23vv3J972o0Vkmzey+G+v3DEi8n5/lCEih4jIThF5R+A8fr34+/01III90Qibgp/9hWfPwqj1I4I9XBFZLiI/9xrByMZMRH7q1erfIiKnJp3T+3vYK2a2xS9oFrZFRO4QkSHv7+O8c6wXkau9+k7+Pdjb+3tvrwxE4r0TkSNF5Efe+W+WWjnxJP4KGAfWAIuB/+e/oar3qOqTMZ+bRa0kxS9VdUXKOYwWY0JgFMFC4I3UShevEZE51Kp1/rlXyOs04POB/e/yRhanAVHlCz7BzFIOvd45CstmFpHjgIOp9XoXA0dGFR9T1aNUdQlwNjBDiCL4gKoeSa2+/0dE5BXUKntKhA17A+cBb/Lu3QjwsQyXMXXvvNpQXwDe4Z3/a8C/pHz+JWAvYLaqTqqqa6mFjwM7VfWsDLYaLWJWqw0wOpKrVHUS+KWI/DdwKPAIcKmILAYmgFcF9v9Tr7TzHwFnBg8kIkdS67CEV4nqA3YALw9tP1tE3gu8AJwTWDTmIhE5z/v7oMD+B3nnBrhaVYMN43Hevw3e6z2oCcOdIRv/ALgdWAC8J/BW3Dk/IiJv9/7e3zvmJmAfEdlLVYPrWrwBeDVwd628E7OplTLxuV1EJqgJ4zQi7t0hwOHArd6xeoG4Hr3PN6l9V/9HRP4U+Iyqfi/lM1BbtOcoEXmVqv6Xw/5GCzEhMIogXLdEqfWWnwIWUWucdgTev0tVT/R6v+tE5LuB9z5JrQf8D/4Gb4TRo6rbvQYtyGdV9d9F5E3AZ4A/8bYv9xuwkDvoV6q6WETmAhtFJNjICfApVf1K4sXWKlQeJiJHUeu9+/WHZpxTRI6mVqzuKM/+O4A5qjouIucDd4lIlZoo+jbcqqpBgQlyjKr+1rt3YbEM3zsBtqjqUUnXE7q2l4CPi8h24ErgZhEZUdVfp3z0TuAbwE0i8qd+NU+jnJhryCiCd4pIj4gcBLwSeAiYBzzpjRTeR0QPFthOrae/m/f6jd5nHgjt9w6m94qj+B213rMr4975K4FtNwMfCPjkB73e/xRSi4rx7d1BrcedxDzgWU8EDqXW4wdAVb+oqod5bjK/Ub8HWCoif+Sdb66IvCp80Aii7t1DwIAnWIhIRUQO8/4+U0TODB9ERA6W2qQvwC+BbcBch/OjqmuBi4AfiFe11SgnNiIwiuAh4EfUqjh+UFV3iMiXgLUi8k5qbpQXAvv7rqE51FwP27ye/sHU5hmm8FwqHwLeH3PuD4vIMmqN1bkOth4oIj+mJkB3quov/FGGqt4iIn8M/NTb9jy1OYynA5//Q+D7UtthFnBWyvl+AHxQahVMH6LW0MeiqltF5P3AFQHBOQ9Ic7fMuHeq+pI3afx5EZnn2XsJsIWa++7uiOMcSq1nPwicSq0S5/0AIvJp4C+AuSLyOHC5ql4QOucaEdkHuFZEjlPVHRilw6qPGrkiIl8Hrnf0IxslQUSuB07xXEFR718QbuSNzsFGBIZhoKonpuxyRzPsMFqDjQgMwzC6HJssNgzD6HJMCAzDMLocEwLDMIwux4TAMAyjyzEhMAzD6HJMCAzDMLqc/w+CkJDUhe387gAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Разброс предсказаний может показать перекос, если есть\n",
    "plt.scatter(y_test, pred) \n",
    "plt.xlabel('Правильные значение, $1K')\n",
    "plt.ylabel('Предсказания, $1K')\n",
    "plt.axis('equal')\n",
    "plt.xlim(plt.xlim())\n",
    "plt.ylim(plt.ylim())\n",
    "plt.plot([-100, 100], [-100, 100])\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "id": "ad65e860",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAX4AAAEGCAYAAABiq/5QAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAVcklEQVR4nO3dfZQldX3n8fcHxIDh+TCQiXEYzbIG1rMMZIJkSVgQYxCOAkazIcYQo2dMjmbRZc9K1I2YbJQkqLtiYjIKcTSIh6gsCCaGZXlYdxUccHhyoig7ZjEjDyICWTYKfPePqjaXpme6eqbr3ttd79c5fbqqbtWtb3XNfLr6d3/1q1QVkqTh2GXSBUiSxsvgl6SBMfglaWAMfkkaGINfkgbmaZMuoIsDDjigVq9ePekyJGlJuemmm+6vqhWzly+J4F+9ejUbN26cdBmStKQk+cZcy23qkaSBMfglaWAMfkkaGINfkgbG4JekgTH4JWlgDH5JGhiDX5IGxuCXpIFZEnfuDt3qs69c0Ppbzj25p0okLQde8UvSwBj8kjQwBr8kDYzBL0kDY/BL0sDYq2cR2OtG0lLiFb8kDYzBL0kDY/BL0sAY/JI0MAa/JA2MwS9JA2PwS9LAGPySNDC9BX+S3ZPcmOSWJHckeUe7fP8kVyW5s/2+X181SJKeqs8r/n8EXlBVhwNrgBOTHA2cDVxdVYcAV7fzkqQx6S34q/FIO7tb+1XAKcCGdvkG4NS+apAkPVWvbfxJdk2yCbgXuKqqbgAOqqqtAO33A/usQZL0ZL0Gf1U9XlVrgB8DjkryvK7bJlmXZGOSjffdd19vNUrS0IylV09VPQhcC5wI3JNkJUD7/d5tbLO+qtZW1doVK1aMo0xJGoQ+e/WsSLJvO70H8ELgb4HLgTPa1c4ALuurBknSU/U5Hv9KYEOSXWl+wVxSVVck+TxwSZLXAH8HvKLHGiRJs/QW/FV1K3DEHMu/DZzQ134lSdvnnbuSNDDL/tGLPhZRkp7MK35JGhiDX5IGxuCXpIEx+CVpYAx+SRqYZd+rZxottKeRJC0mr/glaWAMfkkaGINfkgbG4JekgTH4JWlgDH5JGhiDX5IGxuCXpIEx+CVpYAx+SRoYg1+SBsbgl6SBMfglaWAMfkkaGINfkgamt+BP8qwk1yTZnOSOJGe2y89J8s0km9qvk/qqQZL0VH0+iOUx4KyqujnJXsBNSa5qX3tvVZ3X474lSdvQW/BX1VZgazv9cJLNwDP72p8kqZuxtPEnWQ0cAdzQLnpDkluTXJhkv21ssy7JxiQb77vvvnGUKUmD0HvwJ9kT+CTwxqp6CPgA8OPAGpq/CN4913ZVtb6q1lbV2hUrVvRdpiQNRq/Bn2Q3mtC/qKo+BVBV91TV41X1BPBB4Kg+a5AkPVmfvXoCXABsrqr3jCxfObLaacDtfdUgSXqqPnv1HAO8CrgtyaZ22VuA05OsAQrYAryuxxokSbP02avnc0DmeOkzfe1TkjS/Pq/4tUSsPvvKBa2/5dyTe6pE0jg4ZIMkDYzBL0kDY/BL0sAY/JI0MAa/JA2MvXqWoYX20hkHew5J08MrfkkaGINfkgbG4JekgTH4JWlgDH5JGhiDX5IGxuCXpIEx+CVpYDoFf5J9krx35uHnSd6dZJ++i5MkLb6uV/wXAg8Bv9h+PQT8eV9FSZL603XIhh+vql8YmX/HyOMUJUlLSNcr/keT/MzMTJJjgEf7KUmS1KeuV/y/CWxo2/UDPAD8Wl9FSZL60yn4q2oTcHiSvdv5h/osSpLUn669eg5L8gZgD+CPknwiyRH9liZJ6kPXNv6PAc8FbgBuBC4BPrS9DZI8K8k1STYnuSPJme3y/ZNcleTO9vt+O3MAkqSF6Rr8u1TVbwHfq6oLquqSDts+BpxVVYcCRwOvT3IYcDZwdVUdAlzdzkuSxqTrh7t7JnkZ8LQkp9GE/t7b26CqtgJb2+mHk2wGngmcAhzXrrYBuBZ484IrlyTtkK7Bfx3wkvb7S9tl13fdSZLVwBE0TUUHtb8UqKqtSQ7cxjbrgHUAq1at6rorSdI8ugb/+VV1847sIMmewCeBN1bVQ0k6bVdV64H1AGvXrq0d2bck6am6tvFv94PcbUmyG03oX1RVn2oX35NkZfv6SuDeHXlvSdKO6Rr8T0uyX9sj5wdf29sgzaX9BcDmqnrPyEuXA2e002cAly24aknSDuva1PNc4Caau3ZnFPCc7WxzDPAq4LaRcX3eApwLXJLkNcDfAa9YSMGSpJ3TNfi/XFULumGrqj7Hk39RjDphIe8lSVo8PohFkgam6xX/T/daxRRZffaVky5BknrV9Yr/00n2nZlpP+j9bD8lSZL61DX4V1TVgzMzVfUdYM4bryRJ061r8D+e5Ae3zyY5mKZXjyRpienaxv9W4HNJrmvnj6UdTkGStLR0fRDLXyc5kmaUzQBvqqr7e61MktSLTsHf3oV7IvCcqvrdJKuSHFVVN/ZbnoZqob2rtpx7ck+VSMtP1zb+P6Hp0nl6O/8w8Me9VCRJ6lXXNv7nV9WRSb4ETa+eJE/vsS5JUk+6XvF/P8mutD15kqwAnuitKklSb7oG//uAS4EDk/w+8Dngnb1VJUnqTddePRcluYlmcLUAp1bV5l4rkyT1omuvnv1pHphy8eiyqnqgr8IkSf3o+uHuTTTt+wFW0jxEfb7x+CVJU6hrU8+zZ6aTfGmhY/NLkqbHgsbjb7tw2o1Tkpawrm38n24nDwU+1l85kqS+dW3jP4+m3/7dVfW/e6xHktSzrsF/28xE28MHAHv1DJNPKZOWtq7Bfz9wD/Ao//QAdXv1SNIS1PXD3XXA3cC7gUOq6tlVZehL0hLUKfir6kPAzwA/BPyvJK/stSpJUm86BX+SlwEnA1uADwBvTnLLPNtcmOTeJLePLDsnyTeTbGq/TtqJ2iVJO6BrG/9LZs3f1GGbDwPvBz4ya/l7q+q8jvuVJC2yrnfuvnqhb1xV1ydZveCKJEm96noD1+VzLa+ql+7APt+Q5FeBjcBZVfWdbexzHe0D3VetWrUDu5EkzaVrU8+hwGsXYX8fAH6Ppivo79H0Evr1uVasqvXAeoC1a9fWIuxbkkT34H+4qq7b2Z1V1T0z00k+CFyxs+8pSVqYrv34D0/yYJJvJbk5yflJDljozpKsHJk9Dbh9W+tKkvrR9cPdXZPsAuwB/Cjwi8AGmi6ec0pyMXAccECSu4G3A8clWUPT1LMFeN1O1C5J2gFdm3qoqieAfwDuBH4/yW/Ns/7pcyy+YGHlSZIWW+fgT/JS4Nh29rqqOr+fkiRJfep65+67gDOBL7df/7ZdJklaYrpe8Z8MrGmbe0iyAfgS8Nt9FSZJ6sdCHr2478j0PotchyRpTLpe8b8L+FKSa2jG4z8WeEtvVUmSetO1O+fFSa4Ffoom+N9cVd/qszBJUj+2G/xJTq6qKwGqaitwebt8ryTnV9V2u3RK02qhj4/ccu42b1mRlpz52vj/S5LXjC5I8svArcC9vVUlSerNfE09PwtcmeSZwMeBPwG+B7ywqr7ed3GSpMW33Sv+tnnnX9P8ArgV+FBVnWToS9LSNW93zqp6GHgxcAnwy0l2770qSVJv5vtw92GaAdWg6c3zw8ADSR4Hqqr27rk+SdIi227wV9Ve4ypEkjQeC7lzV5K0DBj8kjQwBr8kDYzBL0kDY/BL0sAY/JI0MAa/JA2MwS9JA2PwS9LA9Bb8SS5Mcm+S20eW7Z/kqiR3tt/362v/kqS59XnF/2HgxFnLzgaurqpDgKvbeUnSGPUW/FV1PfDArMWnABva6Q3AqX3tX5I0t64PW18sB7Vj/FNVW5McuK0Vk6wD1gGsWrVqTOVpqVrooxSlIZvaD3eran1Vra2qtStWrJh0OZK0bIw7+O9JshKg/e5zeyVpzMYd/JcDZ7TTZwCXjXn/kjR4fXbnvBj4PPDcJHcneQ1wLvBzSe4Efq6dlySNUW8f7lbV6dt46YS+9ilJmt+4e/VIg7AjvYy2nHtyD5VITzW1vXokSf0w+CVpYAx+SRoYg1+SBsbgl6SBMfglaWAMfkkaGINfkgbG4JekgTH4JWlgDH5JGhiDX5IGxuCXpIEx+CVpYAx+SRoYg1+SBsbgl6SBMfglaWB89KLUwY48SnGpW+gx++jIpcMrfkkaGINfkgZmIk09SbYADwOPA49V1dpJ1CFJQzTJNv7jq+r+Ce5fkgbJph5JGphJXfEX8DdJCvizqlo/e4Uk64B1AKtWrRpzedL42YtG4zKpK/5jqupI4MXA65McO3uFqlpfVWurau2KFSvGX6EkLVMTCf6q+vv2+73ApcBRk6hDkoZo7MGf5IeT7DUzDbwIuH3cdUjSUE2ijf8g4NIkM/v/WFX99QTqkKRBGnvwV9VdwOHj3q8kqWF3TkkaGINfkgbG4JekgTH4JWlgDH5JGhiDX5IGxuCXpIHx0YvSEjXEx0FqcXjFL0kDY/BL0sAY/JI0MAa/JA2MwS9JA2OvHkkTMY5eST6ecm5e8UvSwBj8kjQwBr8kDYzBL0kDY/BL0sAY/JI0MHbnlKTWNA5810eXVK/4JWlgDH5JGpiJBH+SE5N8JcnXkpw9iRokaajGHvxJdgX+GHgxcBhwepLDxl2HJA3VJK74jwK+VlV3VdX3gI8Dp0ygDkkapEn06nkm8H9G5u8Gnj97pSTrgHXt7CNJvrKD+zsAuH8Ht50WHsP0WA7H0csx5A8W+x23q9MxjLmmhRrHMRw818JJBH/mWFZPWVC1Hli/0ztLNlbV2p19n0nyGKbHcjgOj2E6TPIYJtHUczfwrJH5HwP+fgJ1SNIgTSL4vwgckuTZSZ4O/BJw+QTqkKRBGntTT1U9luQNwGeBXYELq+qOHne5081FU8BjmB7L4Tg8hukwsWNI1VOa1yVJy5h37krSwBj8kjQwyyb45xsGIo33ta/fmuTISdS5PR2O4bgk302yqf36nUnUuT1JLkxyb5Lbt/H6UjgP8x3DUjgPz0pyTZLNSe5IcuYc60z1ueh4DFN9LpLsnuTGJLe0x/COOdYZ/3moqiX/RfMh8deB5wBPB24BDpu1zknAX9HcR3A0cMOk696BYzgOuGLStc5zHMcCRwK3b+P1qT4PHY9hKZyHlcCR7fRewFeX4P+JLscw1eei/dnu2U7vBtwAHD3p87Bcrvi7DANxCvCRanwB2DfJynEXuh3LYiiLqroeeGA7q0z7eehyDFOvqrZW1c3t9MPAZpq75kdN9bnoeAxTrf3ZPtLO7tZ+ze5RM/bzsFyCf65hIGb/A+myziR1re+n2z8b/yrJvxhPaYtq2s9DV0vmPCRZDRxBc7U5asmci+0cA0z5uUiya5JNwL3AVVU18fOwXJ7A1WUYiE5DRUxQl/puBg6uqkeSnAT8V+CQvgtbZNN+HrpYMuchyZ7AJ4E3VtVDs1+eY5OpOxfzHMPUn4uqehxYk2Rf4NIkz6uq0c+Pxn4elssVf5dhIKZ9qIh566uqh2b+bKyqzwC7JTlgfCUuimk/D/NaKuchyW40gXlRVX1qjlWm/lzMdwxL5VwAVNWDwLXAibNeGvt5WC7B32UYiMuBX20/QT8a+G5VbR13odsx7zEk+ZEkaaePojl/3x57pTtn2s/DvJbCeWjruwDYXFXv2cZqU30uuhzDtJ+LJCvaK32S7AG8EPjbWauN/Twsi6ae2sYwEEl+o339T4HP0Hx6/jXg/wKvnlS9c+l4DC8HfjPJY8CjwC9V2y1gWiS5mKanxQFJ7gbeTvOB1pI4D9DpGKb+PADHAK8CbmvblwHeAqyCJXMuuhzDtJ+LlcCGNA+g2gW4pKqumHQ2OWSDJA3McmnqkSR1ZPBL0sAY/JI0MAa/JA2MwS9JA2Pwa9El+YkkN7SjEm5KckGSZ0y6rmmVZFWSj7Y/r9v7ugGpHcnyuFnLXtGOGvlEkrWz1r1iZP4/Jflskh/qozaNl8GvPmwFfr6qjqqqNcBDwBsnWtGUSrI7cDHNjUrPr6rnVdX9Peznd4E/By5sA3zmHp7bgZcB129n27fS9Kk/tar+cbFr0/gZ/Fp0VfXd9vZ0kuwC7A7MzF8768rykfb7nkmuTnJzktuSnNIun33luWXmijjJr4z8VfFn7U0yP3jPdnptkmvb6XOS/Pt2+oQkNVNLkhcl+Xy7/79sx4d5kiRrknwhzZjplybZb/YxJXl/kl9rp1+b5Lx2+sNJXj6yvNrjeAGwB/B+mhuV/mCOn82PtMd4+BzH9z9Gfz5zSXIozY1OZwK/Dvw74In2XG2uqq9sZ9uzaG4ueklVPbq9/WjpMPjViyR7tHdb3gccDnxwnk3+H3BaVR0JHA+8u70V/wnmGMSqDbN/AxzT/lXxOPDKBZT4dpo7JWkD+G3AC9v9b6QJx9k+Ary5qv4lcFv7HgvSXuH/Bs1IjQAraEZiPB5YA/xUklNH1t+bZuCxN1XVLbPe62Rgnw67fYxmPPtnAFTVHVX1RIftjmlrffHI0MJaBgx+9aKqHm0D+SCah8q8deTli9or2E00V7vQhPs7k9wK/DeaMDyIZgCrQ9vAHHUC8JPAF9v3OYHmITYAe4y8/0Wza0vyCzRjI32zXXQ0cBjwP9ttzgAOnrXNPsC+VXVdu2gDzQNbFur17bYzV88BPltV91XVY229M++7C3ApcE9VXTOrntD8TN853w6r6k7gHOB3gPVJ/mP7l9h8vtbW96IO62oJWRZj9Wh6tWMQfRz4DyOLX1lVG+FJzRavpLn6/cmq+n6SLcDuVXVXko8BNyf5HvCj7foBNlTVb8+x25lfOrRNMOeNvLZrW8vJwCdG3uuqqjp95452XnsDpwP/CjirXTZ7mOFRewCfBk5J8oKq+u8jr51OM9Ljt7rsuKouSPJ14ABgHc3P+6PzbHZPu97VSb49+5ePli6v+LXokhySZFU7HeClwI3zbLYPcG8b+sczcsVdVW+rqsPaMJ8ZrvZq4OVJDmz3s3+Sg2e/6Rx+Bbhy1geoXwCOSfLP2vd6RpJ/PrpRVX0X+E6Sn20XvQq4joV5E/C+9glrM24CXpDkgPYzitNH3vcfquo/A68D3pdmdEdo/t++CfjD0TdPclSSj8zeaZIDR3oK3Q/cRdP0M6+q+irNh79/kWRNl200/bziVx/2pGnOeXo7fx3wrnm2uQj4dJKNwCaeOnTtk1TVl5O8Dfibttni+zTNKN+YZz8HAe+d9V73tR/IXjzSXfFtNM94HXUG8KdpuqbexZNHUfxQ+9fLc4AXJXltu6/LRtYJ8Bez9v2NJOfQ9Kp5nOaX0mWz1vlq+1fPO2j+WtkD+ERVPdj8Xv2BVfxTE9KovYH1NH9R7Q58BZj5kPs04Pz2tSuTbKqqn5+1/y8meTVweZLjq+rrc+xDS4ijc0rLRJI/Aj5aVbdu4/XjAKrq2vFVpWlk8EsDkea5tVTVlslWokkz+CVpYPxwV5IGxuCXpIEx+CVpYAx+SRoYg1+SBub/A/0JL9N+UeDEAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Разность предсказанного и правильного ответа\n",
    "error = pred - y_test\n",
    "#Построение гистограммы\n",
    "plt.hist(abs(error), bins = 25)\n",
    "plt.xlabel(\"Значение ошибки, $1K\")\n",
    "plt.ylabel(\"Количество\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5e0c592e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
